'use strict';
// Exercises exact shipped functions. All signatures below are public synthetic fixtures, not hardware.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const FILE=process.argv[2],OUT=process.argv[3],{A,ctx}=require('./load.cjs').load(FILE),rows=[];
const range=(process.env.TEST_RANGE||'1:999').split(':').map(Number);let index=0;
function test(name,fn){index++;if(index<range[0]||index>range[1])return;try{fn();rows.push({id:index,name,status:'passed'});console.log('PASS',index,name)}catch(e){rows.push({id:index,name,status:'failed',error:e.stack});console.error('FAIL',index,name,e.message)}}
const hex=x=>A.K.encode(x),from=x=>A.K.decode(x),spec=A.Hp(),root=A.up(spec.mnemonic),refs=A.Np(spec,root),raw=from(refs[0].txHex);
const common=(new Date()).toISOString();
function signed(version=2,reduce=false,final=false){const p=A.wp({...spec,psbtVersion:version},root),r=A.ap.fromRaw(raw);for(let i=0;i<spec.inputs.length;i++){const w=r.getInput(i).finalScriptWitness;p.updateInput(i,{partialSig:[[w[1],w[0]]]},true)}if(final)p.finalize();if(reduce){p.inputs=p.inputs.map(x=>Object.fromEntries(Object.entries(x).filter(([k])=>['txid','index','sequence','partialSig','finalScriptWitness','finalScriptSig'].includes(k))));p.outputs=p.outputs.map(x=>({amount:x.amount,script:x.script}))}return p}
function read(bytes,version=2){return A.zp({...spec,psbtVersion:version},{kind:'psbt',bytes},refs,root)}
function check(p,version=2){return read(p.toPSBT(version),version)}
function compact(n){if(n<253)return Buffer.from([n]);if(n<=65535){let b=Buffer.alloc(3);b[0]=253;b.writeUInt16LE(n,1);return b}let b=Buffer.alloc(5);b[0]=254;b.writeUInt32LE(n,1);return b}
function pack(maps){return new Uint8Array(Buffer.concat([Buffer.from('70736274ff','hex'),...maps.flatMap(m=>[...m.values()].flatMap(f=>{let k=Buffer.from(f.key,'hex'),v=Buffer.from(f.value,'hex');return [compact(k.length),k,compact(v.length),v]}).concat([Buffer.from([0])]))]))}
function metaReport(status='expected',result='match',tx='a',test=1){return {createdAt:common,test,scenario:'small',completed:result!=='incomplete',result,evidence:{transactionId:tx.repeat(64),artifactSha256:'b'.repeat(64)},metadata:status===null?null:{status},signingPolicy:{id:'compatible'}}}
function aggregate(checks){ctx.auditChecks=checks;return JSON.parse(JSON.stringify(vm.runInContext('em(auditChecks)',ctx)))}
function app(){const a=A.Fv(),f=v=>({value:String(v),error:null});a.$refs={};a.$nextTick=async()=>{};a.seed=f(spec.mnemonic);a.lockTime=f(spec.lockTime);a.psbtVersion='2';a.inputs=spec.inputs.map((v,i)=>({id:i,utxoId:f(v.txid+':'+v.vout),amount:f(v.amountSats),pathSuffix:f('0h/'+v.change+'/'+v.addressIndex),sequence:f(v.sequence)}));a.outputs=[{id:9,amount:f(spec.outputs[0].amountSats),dest:f('m/84h/0h/0h/0/18')}];a.acknowledged=true;a.recompute();assert(a.transactionReady);return a}
for(const version of [0,2])for(const final of [false,true])test(`A exact ALL retained in uniform reduced v${version} ${final?'final':'partial'} response`,()=>{const p=signed(version,true,final);p.inputs.forEach(i=>i.sighashType=1);const r=check(p,version);assert(r.ok&&r.matched);assert(r.metadata.reducedResponse);assert.equal(r.metadata.unexpected,0);assert.equal(r.metadata.policy,'psbt-envelope-v3');assert.equal(r.metadata.status,'expected')});
for(const value of [0,2,3,129,130,131,255])test(`A non-ALL sighash ${value} still fails semantic verification`,()=>{const p=signed(2,true);p.inputs.forEach(i=>i.sighashType=value);const r=check(p);assert(!r.ok);assert(!r.metadata)});
for(const [label,value,key] of [['too short','01','03'],['too long','0100000000','03'],['big endian','00000001','03'],['nonempty key data','01000000','0300']])test('A malformed sighash field '+label+' never becomes reduced success',()=>{const m=A.tbwPsbtMaps(signed(2,true).toPSBT(2));m[1].set(key,{key,value});const r=read(pack(m));assert(!r.ok);assert(!r.metadata)});
for(const [label,mutate] of [['signature corruption',p=>p.inputs[0].partialSig[0][1][8]^=1],['foreign key',p=>p.inputs[0].partialSig[0][0]=root.publicKey],['missing signature',p=>delete p.inputs[0].partialSig],['changed amount',p=>p.outputs[0].amount++],['changed locktime',p=>p.global.fallbackLocktime++]])test('A retained ALL does not bypass '+label,()=>{const p=signed(2,true);p.inputs.forEach(i=>i.sighashType=1);mutate(p);assert(!check(p).ok)});
for(const version of [0,2])test(`A trigger matrix selective removals and unknown additions remains review v${version}`,()=>{for(const mutate of [p=>delete p.inputs[0].witnessUtxo,p=>delete p.inputs[0].bip32Derivation,p=>delete p.outputs[0].bip32Derivation,p=>{p.finalize();delete p.inputs[0].witnessUtxo},p=>p.global.proprietary=[[Uint8Array.of(1,120,0),Uint8Array.of(1)]]]){const p=signed(version);mutate(p);const r=check(p,version);assert(r.ok&&r.matched);assert.equal(r.metadata.status,'unexpected')}});
for(const version of [0,2])test(`B actual per-map reversal is informational and positions reconstruct v${version}`,()=>{const p=signed(version);const maps=A.tbwPsbtMaps(p.toPSBT(version)).map(m=>new Map([...m].reverse()));const r=read(pack(maps),version);assert(r.ok&&r.matched);assert(r.metadata.fieldOrderChanged>=2);assert.notEqual(r.metadata.status,'unexpected');assert.equal(r.metadata.fieldOrderBasis,'original-prepared-psbt');for(let n=0;n<maps.length;n++){const scope=n===0?'global':n<=2?'input':'output',i=n===0?null:n<=2?n-1:n-3;const fields=r.metadata.fields.filter(f=>f.scope===scope&&f.index===i&&f.afterPosition!==null).sort((a,b)=>a.afterPosition-b.afterPosition);assert.equal(JSON.stringify(fields.map(f=>f.key)),JSON.stringify([...maps[n].keys()]));assert(Object.isFrozen(r.metadata.fieldOrder))}});
for(const version of [0,2])test(`B signature addition/removal alone is not called retained reordering v${version}`,()=>{const original=A.tbwPsbtMaps(A.Tp({...spec,psbtVersion:version},root)),full=A.tbwPsbtMaps(signed(version).toPSBT(version));for(let i=0;i<full.length;i++){const ordered=new Map(original[i]);for(const [k,v] of full[i])if(!ordered.has(k))ordered.set(k,v);full[i]=ordered}const r=read(pack(full),version);assert(r.ok&&r.matched);assert.equal(r.metadata.fieldOrderChanged,0);const reduced=check(signed(version,true),version);assert.equal(reduced.metadata.unexpected,0);assert.equal(reduced.metadata.fieldOrderChanged,0)});
test('B positions include newly inserted keys even without relative common-key reordering',()=>{let m=A.tbwPsbtMaps(signed().toPSBT(2));const signature=[...m[1]].find(([k])=>k.startsWith('02'));m[1]=new Map([signature,...[...m[1]].filter(([k])=>k!==signature[0])]);const r=read(pack(m));assert(r.ok&&r.matched);assert.equal(r.metadata.fieldOrderChanged,0);assert.equal(r.metadata.fields.find(f=>f.scope==='input'&&f.index===0&&f.type===2).afterPosition,0);assert(r.metadata.limitation.includes('added-field')||r.metadata.limitation.includes('Added-field'))});
test('B version conversion has explicit same-version comparison basis',()=>{const r=read(signed(0).toPSBT(0),2);assert(r.ok&&r.matched);assert(r.metadata.versionConversion);assert.equal(r.metadata.fieldOrderBasis,'same-version-local-reconstruction')});
test('B reordered fields with unknown payload do not suppress a review finding',()=>{const p=signed();p.global.proprietary=[[Uint8Array.of(1,120,0),Uint8Array.of(1)]];const m=A.tbwPsbtMaps(p.toPSBT(2)).map(m=>new Map([...m].reverse()));const r=read(pack(m));assert(r.ok&&r.matched);assert.equal(r.metadata.status,'unexpected');assert(r.metadata.fieldOrderChanged>0)});
test('B raw transaction explicitly has no order assessment',()=>{const r=A.zp(spec,{kind:'tx',bytes:raw},refs,root);assert(r.ok&&r.matched);assert.equal(r.metadata.fieldOrderAssessed,false);assert.equal(r.metadata.fieldOrderChanged,0)});
test('B duplicate keys and altered byte values remain rejected or visible',()=>{const p=signed();p.outputs[0].bip32Derivation[0][1].path[4]++;const r=check(p);assert.equal(r.metadata.status,'unexpected');const m=A.tbwPsbtMaps(signed().toPSBT(2));const b=pack(m);assert.throws(()=>A.tbwPsbtMaps(new Uint8Array([...b,1,0])))});
test('C three mutually exclusive outcome counts include metadata and sum to checked',()=>{const j=new A.TbwSessionJournal();j.record(metaReport('expected','match','a'));j.record(metaReport('unexpected','match','b'));j.record(metaReport('expected','mismatch','c'));const r=aggregate(j.checks());assert.deepEqual([r.checked,r.matched,r.review,r.differed],[3,1,1,1]);assert.equal(r.countPolicy,'distinct-transaction-worst-observed-v2');assert(j.checks().every(e=>e.metadataStatus))});
for(const sequence of [['expected','unexpected'],['unexpected','expected'],['expected','unexpected','expected']])test('C same txid worst file finding retained: '+sequence.join(' -> '),()=>{const j=new A.TbwSessionJournal();for(const s of sequence)j.record(metaReport(s));const r=aggregate(j.checks());assert.deepEqual([r.checked,r.matched,r.review,r.differed],[1,0,1,0]);assert.equal(j.history().length,sequence.length)});
for(const sequence of [['match','mismatch','match'],['mismatch','match','match']])test('C mismatch dominates later review/match: '+sequence.join(' -> '),()=>{const j=new A.TbwSessionJournal();for(const s of sequence)j.record(metaReport('unexpected',s));const r=aggregate(j.checks());assert.deepEqual([r.checked,r.matched,r.review,r.differed],[1,0,0,1])});
for(const s of [null,'unrecognized'])test('C unknown/missing metadata is review rather than invented clean status '+s,()=>{const j=new A.TbwSessionJournal();j.record(metaReport(s));const r=aggregate(j.checks());assert.equal(r.matched,0);assert.equal(r.review,1)});
test('C incomplete operations excluded from completed summary and retained in history',()=>{const j=new A.TbwSessionJournal();j.record(metaReport('unexpected','incomplete'));assert.equal(aggregate(j.checks()).checked,0);assert.equal(j.history().length,1)});
test('C projected immutable current result includes the new review before journal commit',()=>{const a=app();const p=signed();p.outputs[0].bip32Derivation[0][1].path[4]++;a.acceptArtifact(hex(p.toPSBT(2)));assert.equal(a.resultState,'match');assert.equal(a.resultDisplayState,'review');const r=a.report();assert.deepEqual([r.session.matched,r.session.review,r.session.checked],[0,1,1]);assert.equal(r.sessionChecks[0].metadataStatus,'unexpected');assert.equal(JSON.stringify(a.exportEvidence().report),JSON.stringify(r));assert.equal(JSON.stringify(a.sessionSummary),JSON.stringify(r.session));a.destroy()});
test('C raw transaction is a matched signature with metadata not applicable',()=>{const a=app();a.acceptArtifact(refs[0].txHex);assert.equal(a.sessionSummary.matched,1);assert.equal(a.sessionSummary.review,0);assert.equal(a.report().session.matched,1);a.destroy()});
test('C guided status stops on review, excludes it from matched, preserves end record',()=>{const j=new A.TbwSessionJournal(),plan=j.plan(1,{walletSession:'fixture',rootPublicKey:hex(root.publicKey),fingerprint:'00000000',policy:'compatible',psbtVersion:'0'});j.apply(plan);j.record(metaReport('unexpected'));assert.equal(j.status().phase,'halted');assert.equal(j.status().matched,0);assert.equal(j.status().review,1);const before=j.report();j.rollback();assert.equal(j.status().review,1);assert.equal(before.status.phase,'halted');assert(Object.isFrozen(before.status))});
test('D metadata preview is capped and full immutable evidence fields are preserved',()=>{const a=app(),fields=Array.from({length:1000},(_,i)=>({scope:'global',index:null,key:'aa'.repeat(5000)+i.toString(16),type:252,change:'added',classification:'unexpected',field:'proprietary',reason:'unrecognized'})),meta=A.tbwFreeze({fields,status:'unexpected'});Object.defineProperty(a,'metadataSummary',{get:()=>meta});const before=JSON.stringify(meta),preview=a.metadataDetails;assert.equal(preview.length,32);assert.equal(a.metadataDetailCount,1000);assert(preview.every(f=>f.key.length<=129));assert.equal(new Set(preview.map(f=>f.displayId)).size,32);assert(a.metadataDetailNotice.includes('32 of 1000'));assert.equal(JSON.stringify(meta),before);a.destroy()});
test('D preview empty and exact-boundary shapes neither clip counts nor fabricate findings',()=>{const a=app();let meta=null;Object.defineProperty(a,'metadataSummary',{get:()=>meta});assert.equal(a.metadataDetails.length,0);for(const n of [1,32,33]){meta=A.tbwFreeze({fields:Array.from({length:n},(_,i)=>({key:'ab'.repeat(64),classification:'unexpected'}))});assert.equal(a.metadataDetails.length,Math.min(n,32));assert(a.metadataDetails.every(f=>f.key.length===128));assert.equal(a.metadataDetailCount,n)}a.destroy()});
test('D actual large key and many fields remain available in full report, without expanding preview',()=>{const a=app(),m=A.tbwPsbtMaps(signed().toPSBT(2));for(let i=0;i<100;i++){const key='fa'+i.toString(16).padStart(4,'0');m[0].set(key,{key,value:'00'})}let key='fa'+'ab'.repeat(32768);m[0].set(key,{key,value:'01'});a.acceptArtifact(hex(pack(m)));assert.equal(a.resultDisplayState,'review');assert.equal(a.metadataDetails.length,32);assert(a.report().metadata.fields.some(f=>f.key===key));assert(a.exportEvidence().report.metadata.fields.some(f=>f.key===key));assert(a.report().metadata.unexpected>=101);assert(!JSON.stringify(a.exportEvidence()).includes(spec.mnemonic));a.destroy()});
test('D truncation cannot mutate completed artifact or session on subsequent getter calls',()=>{const a=app(),p=signed();p.global.proprietary=[[Uint8Array.of(1,120,0),Uint8Array.of(65)]];a.acceptArtifact(hex(p.toPSBT(2)));const original=JSON.stringify(a.exportEvidence()),journal=JSON.stringify(a.sessionHistory);for(let i=0;i<10;i++){a.metadataDetails;a.metadataDetailNotice;a.metadataOrderExplanation}assert.equal(JSON.stringify(a.exportEvidence()),original);assert.equal(JSON.stringify(a.sessionHistory),journal);a.destroy()});
test('Known BIP84 receive/change addresses independently supplied in audit remain exact',()=>{const r=A.up('abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about');for(const [suffix,expected] of [["0/0",'bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu'],["0/1",'bc1qnjg0jd8228aq7egyzacy8cys3knf9xvrerkf9g'],["1/0",'bc1q8c6fshw2dlwun7ekn9qwf37cu2rn755upcp6el']])assert.equal(A.Af(r.derive("m/84'/0'/0'/"+suffix).publicKey).address,expected)});
test('Known Dark Skippy attack still produces two valid but different signatures',()=>{const r=A.Up();assert(r.ok&&!r.matched);assert.equal(r.evidence.signaturesVerified,2)});
const r={suite:'Source audit A-D integration and BIP84 known answers',complete:true,total_defined:index,test_range:range.join(':'),sha256:crypto.createHash('sha256').update(fs.readFileSync(FILE)).digest('hex'),passed:rows.filter(r=>r.status==='passed').length,failed:rows.filter(r=>r.status==='failed').length,results:rows};fs.writeFileSync(OUT,JSON.stringify(r,null,2));console.log('TOTAL',r.passed,r.failed,'DEFINED',index);process.exitCode=r.failed?1:0;
