'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto'),{load}=require('./load.cjs');
const FILE=process.argv[2],OUT=process.argv[3],{A,ctx}=load(FILE),results=[];
const range=(process.env.TEST_RANGE||'1:999').split(':').map(Number);let index=0;
const hex=A.K.encode,base=A.Hp(),root=A.up(base.mnemonic),refs=A.Np(base,root);
const field=value=>({value:String(value),error:null});
function application(spec=base){
 const a=A.Fv();a.$refs={};a.$nextTick=async()=>{};
 a.seed=field(spec.mnemonic);a.acknowledged=true;a.lockTime=field(spec.lockTime);a.psbtVersion=String(spec.psbtVersion);
 a.inputs=spec.inputs.map((x,i)=>({id:i,utxoId:field(x.txid+':'+x.vout),amount:field(x.amountSats),pathSuffix:field(x.account+'h/'+x.change+'/'+x.addressIndex),sequence:field(x.sequence)}));
 a.outputs=spec.outputs.map((x,i)=>({id:i+100,amount:field(x.amountSats),dest:field(x.dest.kind==='address'?x.dest.address:`m/84h/0h/${x.dest.account}h/${x.dest.change}/${x.dest.addressIndex}`)}));
 a.recompute();assert.equal(a.buildProblem,'');return a;
}
function snapshot(a){return JSON.stringify([a.stateSignature,a.psbtBase64,a.variants,a.preparedRevision,a.walletSession,a.sessionChecks,a.guidedStatus,a.resultState,a.isTestComplete]);}
async function test(name,f){index++;if(index<range[0]||index>range[1])return;console.log('RUN',index,name);const start=performance.now();try{await f();results.push({name,status:'passed',ms:Math.round(performance.now()-start)});}catch(e){results.push({name,status:'failed',error:e.stack});}console.log(results.at(-1).status,index,name);fs.writeFileSync(OUT,JSON.stringify({complete:false,results},null,2));}
function signed(spec=base){const p=A.wp(spec,root),raw=A.ap.fromRaw(A.K.decode(A.Np(spec,root)[0].txHex),{allowUnknownInputs:true,allowUnknownOutputs:true,disableScriptCheck:true});for(let i=0;i<spec.inputs.length;i++){const w=raw.getInput(i).finalScriptWitness;p.updateInput(i,{partialSig:[[w[1],w[0]]]},true);}return p;}
const native=A.Af(A.fp(root,0,0,111).publicKey,A._d).address;
function twenty(){return {...base,psbtVersion:0,outputs:Array.from({length:20},(_,i)=>({amountSats:BigInt(600+i),dest:i%3===0?{kind:'address',address:native}:{kind:'change',account:0,change:i%2,addressIndex:50+i}}))};}
(async()=>{
await test('C01 workspace transitions preserve exact prepared transaction and policy',async()=>{const a=application(),before=snapshot(a);for(const view of ['advanced','session','test','advanced','test']){assert(await a.openWorkspace(view));assert.equal(snapshot(a),before);}a.destroy();});
await test('C02 unknown workspace rejected without changing state',async()=>{const a=application(),before=snapshot(a);await assert.rejects(a.openWorkspace('untrusted'));assert.equal(a.workspaceView,'test');assert.equal(snapshot(a),before);a.destroy();});
await test('C03 live capture blocks view changes without restarting capture',async()=>{const a=application();a.scan.active=true;const before=snapshot(a);assert.equal(await a.openWorkspace('advanced'),false);assert.equal(a.workspaceView,'test');assert.equal(snapshot(a),before);a.scan.active=false;a.destroy();});
await test('C04 stale deferred workspace focus cannot revive a departed view',async()=>{const a=application(),queue=[],hits=[];a.$nextTick=()=>new Promise(r=>queue.push(r));a.$refs={advancedTitle:{focus:()=>hits.push('advanced')},sessionTitle:{focus:()=>hits.push('session')}};const first=a.openWorkspace('advanced'),last=a.openWorkspace('session');queue.splice(0).forEach(r=>r());await Promise.all([first,last]);queue.splice(0).forEach(r=>r());await Promise.resolve();assert(!hits.includes('advanced'));assert.equal(a.workspaceView,'session');a.destroy();});
await test('C05 epoch change invalidates pending workspace transition',async()=>{const a=application(),queue=[];a.$nextTick=()=>new Promise(r=>queue.push(r));const p=a.openWorkspace('advanced');a.epoch++;queue.splice(0).forEach(r=>r());assert.equal(await p,false);a.destroy();});
await test('C06 completed report stays immutable across all workspaces',async()=>{const a=application();a.acceptArtifact(refs[0].txHex);const report=a.report();for(const v of ['advanced','session','test']){await a.openWorkspace(v);assert.strictEqual(a.report(),report);}a.destroy();});
await test('C07 output review has all 20 exact ordered amounts scripts and roles',()=>{const spec=twenty(),a=application(spec),rows=a.outputReview.outputs,p=A.ap.fromPSBT(A.Ra.decode(a.psbtBase64));assert.equal(rows.length,20);rows.forEach((r,i)=>{assert.equal(r.index,i);assert.equal(r.amountSats,String(spec.outputs[i].amountSats));assert.equal(r.scriptHex,hex(p.getOutput(i).script));assert.equal(r.address,p.getOutputAddress(i));assert.equal(r.role,i%3===0?'Recipient':i%2?'Change':'Self-transfer');});assert(Object.isFrozen(rows)&&Object.isFrozen(rows[0]));a.destroy();});
await test('C08 reviewing 20 outputs cannot re-prepare or change signing references',()=>{const a=application(twenty()),before=snapshot(a);for(let i=0;i<25;i++){a.outputsOpen=!a.outputsOpen;assert(a.outputReview.ok);}assert.equal(snapshot(a),before);a.destroy();});
await test('C09 pending output edit immediately suppresses stale output review',()=>{const a=application(),old=a.psbtBase64;a.outputs[0].amount.value='50000';assert(!a.outputReview.ok);assert.equal(a.outputReview.outputs.length,0);a.recompute();assert(a.outputReview.ok);assert.notEqual(a.psbtBase64,old);assert.equal(a.outputReview.outputs[0].amountSats,'50000');a.destroy();});
await test('C10 malformed output state cannot expose stale destination',()=>{const a=application();a.outputs[0].dest.value='<script>bad</script>';a.invalidate();a.recompute();assert(!a.outputReview.ok);assert.equal(a.outputReview.outputs.length,0);assert(a.buildProblem);a.destroy();});
await test('C11 destroyed test has no output projection or retained public review',()=>{const a=application();a.destroy();assert(!a.outputReview.ok);assert.equal(a.outputReview.outputs.length,0);});
await test('C12 output helper missing dependency produces explicit review problem',()=>{const a=application();vm.runInContext('globalThis.savedReview=tbwOutputReview;tbwOutputReview=()=>{throw Error("injected")}',ctx);try{assert(!a.outputReview.ok);assert(a.outputReview.problem.includes('Do not sign'));}finally{vm.runInContext('tbwOutputReview=savedReview',ctx);a.destroy();}});
const publicData=A.tbwPublicTest(base,root,hex(A.Tp(base,root)),refs);
for(const [label,mutate]of [['missing public test',()=>null],['wrong output count',p=>({...p,outputs:[]})],['mismatched amount',p=>({...p,outputs:p.outputs.map(o=>({...o,amountSats:'1'}))})],['invalid script',p=>({...p,outputs:p.outputs.map(o=>({...o,scriptHex:'00'}))})]]){
 await test('C13 invalid prepared projection rejects '+label,()=>assert.throws(()=>A.tbwOutputReview(mutate(publicData),base)));
}
await test('C14 BTC/sats changes preserve exact public output data',()=>{const a=application();const before=JSON.stringify(a.outputReview);a.amountUnit='sats';assert.match(a.formatReviewAmount('56479'),/56,479 sats/);a.amountUnit='btc';assert.match(a.formatReviewAmount('56479'),/0\.00056479 BTC/);assert.equal(JSON.stringify(a.outputReview),before);a.destroy();});
await test('C15 new transaction exits auxiliary view and closes output disclosure',async()=>{const a=application();await a.openWorkspace('session');a.outputsOpen=true;a.randomizeTransaction('small');assert.equal(a.workspaceView,'test');assert.equal(a.outputsOpen,false);assert.equal(a.testNumber,2);a.destroy();});
await test('C16 verification reveals the correct main result from auxiliary view',async()=>{const a=application();await a.openWorkspace('advanced');a.acceptArtifact(refs[0].txHex);assert.equal(a.workspaceView,'test');assert.equal(a.resultState,'match');a.destroy();});
await test('C17 short export name is content-derived and JSON remains exact',()=>{vm.runInContext('globalThis.savedQp=Qp;globalThis.savedDownload=null;Qp=(text,name,mime)=>{globalThis.savedDownload={text,name,mime}}',ctx);try{const value={schema:'sample',build:A.TBW_BUILD};const name=A.tbwSaveJson(value,'detail'),expected=JSON.stringify(value,null,2);assert.equal(name,'detail-'+crypto.createHash('sha256').update(expected).digest('hex').slice(0,12)+'.json');assert.equal(ctx.savedDownload.text,expected);assert.equal(ctx.savedDownload.mime,'application/json');assert.equal(A.tbwSaveJson(value,'detail'),name);}finally{vm.runInContext('Qp=savedQp',ctx);}});
for(const category of ['../detail','detail/evil','test',null])await test('C18 unsafe export category rejected: '+category,()=>assert.throws(()=>A.tbwSaveJson({},category)));
await test('C19 unrepresentable JSON fails before download',()=>{assert.throws(()=>A.tbwSaveJson(undefined,'record'));const x={};x.x=x;assert.throws(()=>A.tbwSaveJson(x,'record'));});
await test('C20 Save result uses full current evidence rather than summary',()=>{const a=application();a.acceptArtifact(refs[0].txHex);let ev=0,summary=0;a.downloadEvidence=()=>ev++;a.downloadReport=()=>summary++;a.downloadResult();assert.equal(ev,1);assert.equal(summary,0);a.destroy();});
await test('C21 incomplete unparseable result has explicit summary fallback',()=>{const a=application();a.acceptArtifact('bad');let ev=0,summary=0;a.downloadEvidence=()=>ev++;a.downloadReport=()=>summary++;a.downloadResult();assert.equal(ev,0);assert.equal(summary,1);assert.equal(a.resultState,'incomplete');a.destroy();});
await test('C22 failed download leaves result and journal immutable',()=>{const a=application();a.acceptArtifact(refs[0].txHex);const before=snapshot(a),report=a.report();vm.runInContext('globalThis.savedQp=Qp;Qp=()=>{throw Error("full disk simulation")}',ctx);try{a.downloadResult();assert(a.notice.includes('download unavailable'));assert.strictEqual(a.report(),report);assert.equal(snapshot(a),before);}finally{vm.runInContext('Qp=savedQp',ctx);a.destroy();}});
await test('C23 result evidence preserves identities and excludes locally held secrets',()=>{const a=application();a.acceptArtifact(refs[0].txHex);const ev=a.exportEvidence(),text=JSON.stringify(ev);assert.strictEqual(ev.report,a.report());assert.equal(ev.returnedArtifact.hex,refs[0].txHex);assert.equal(ev.report.build.sourceSha256,A.TBW_BUILD.sourceSha256);for(const secret of [base.mnemonic,hex(root.privateKey),root.privateExtendedKey])assert(!text.includes(secret));a.destroy();});
await test('C24 session history is frozen and cannot serve as a second mutable ledger',()=>{const a=application();a.acceptArtifact(refs[0].txHex);const rows=a.sessionHistory;assert(Object.isFrozen(rows)&&Object.isFrozen(rows[0]));assert.throws(()=>rows.push({}));assert.equal(a.sessionChecks.length,1);a.destroy();});
await test('C25 unexpected field finding remains recorded after later clean match',()=>{const a=application(),p=signed();p.global.proprietary=[[Uint8Array.of(1,120,0),Uint8Array.of(65)]];a.acceptArtifact(hex(p.toPSBT(2)));assert.equal(a.resultDisplayState,'review');assert.equal(a.recordedReviewCount,1);a.randomizeTransaction('small');a.acceptArtifact(a.variants[0].txHex);assert.equal(a.resultState,'match');assert.equal(a.recordedReviewCount,1);assert.equal(a.historyTone(a.sessionHistory[0]),'review');a.destroy();});
await test('C26 incomplete finding survives later successful response',()=>{const a=application();a.acceptArtifact('bad');assert.equal(a.recordedIncompleteCount,1);a.acceptArtifact(refs[0].txHex);assert.equal(a.resultState,'match');assert.equal(a.recordedIncompleteCount,1);assert.equal(a.sessionSummary.checked,1);a.destroy();});
await test('C27 duplicate return cannot inflate counts or history',()=>{const a=application();a.acceptArtifact(refs[0].txHex);for(let i=0;i<10;i++)a.acceptArtifact(refs[0].txHex);assert.equal(a.sessionHistory.length,1);assert.equal(a.sessionSummary.checked,1);a.destroy();});
await test('C28 history export retains scope and evidence limitations with no seed',()=>{const a=application();a.acceptArtifact(refs[0].txHex);const history=a.exportHistory(),text=JSON.stringify(history);assert.equal(history.summary.checked,1);assert.equal(history.events.length,1);assert.equal(history.build.sourceSha256,A.TBW_BUILD.sourceSha256);assert(history.scope.includes('not an archive'));assert(!text.includes(base.mnemonic));assert(Object.isFrozen(history));a.destroy();});
await test('C29 failed history export cannot clear earlier review finding',()=>{const a=application();a.acceptArtifact('bad');const before=JSON.stringify(a.exportHistory());vm.runInContext('globalThis.savedQp=Qp;Qp=()=>{throw Error("denied")}',ctx);try{a.downloadHistory();assert.equal(JSON.stringify(a.exportHistory()),before);assert(a.notice.includes('unavailable'));}finally{vm.runInContext('Qp=savedQp',ctx);a.destroy();}});
await test('C30 known malicious example remains separate from journal counts',()=>{const a=application(),before=a.sessionHistory;a.runDemonstration();assert(a.demonstration.analysis.ok&&!a.demonstration.analysis.matched);assert.equal(a.sessionSummary.checked,0);assert.equal(a.sessionHistory.length,before.length);a.destroy();});
await test('C31 expected reduced response policy remains distinct from unexpected fields',()=>{const a=application(),p=signed();for(const input of p.inputs){delete input.witnessUtxo;delete input.bip32Derivation;}for(const output of p.outputs)delete output.bip32Derivation;a.acceptArtifact(hex(p.toPSBT(2)));assert.equal(a.resultDisplayState,'match');assert.equal(a.metadataSummary.status,'expected');assert.equal(a.metadataSummary.reducedResponse,true);a.destroy();});
await test('C32 state tampering never exports a stale completed result',()=>{const a=application();a.acceptArtifact(refs[0].txHex);a.outputs[0].amount.value='1';assert.equal(a.resultState,'unverified');assert(!a.hasEvidence);assert.throws(()=>a.exportEvidence());a.destroy();});
await test('C33 QR/display switching never substitutes reference response for device data',()=>{const a=application();a.psbtQrMode='bbqr';a.amountUnit='sats';a.recompute();assert.equal(a.resultState,'unverified');assert.equal(a.sessionHistory.length,0);assert(!a.hasEvidence);a.destroy();});
await test('C34 full output fixture exported for independent script/amount replay',()=>{const spec=twenty(),a=application(spec);a.acceptArtifact(a.variants[0].txHex);const fixture={rows:a.outputReview.outputs,evidence:a.exportEvidence()};fs.writeFileSync(OUT.replace(/\.json$/,'-outputs.json'),JSON.stringify(fixture,null,2));assert.equal(fixture.rows.length,20);a.destroy();});
const out={suite:'Calm workspace/output/export contracts and faults',complete:true,totalDefined:index,testRange:range,sha256:crypto.createHash('sha256').update(fs.readFileSync(FILE)).digest('hex'),passed:results.filter(x=>x.status==='passed').length,failed:results.filter(x=>x.status==='failed').length,results};fs.writeFileSync(OUT,JSON.stringify(out,null,2));console.log(JSON.stringify({passed:out.passed,failed:out.failed,total:index}));process.exitCode=out.failed?1:0;
})().catch(e=>{console.error(e);process.exitCode=1});
