'use strict';
const fs=require('fs'),assert=require('assert/strict'),{load}=require('./load.cjs');
const FILE=process.argv[2],OUT=process.argv[3],results=[];
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve()};
class Clock{now=0;next=1;jobs=new Map;set=(f,ms=0)=>{const id=this.next++;this.jobs.set(id,{at:this.now+ms,f});return id};clear=id=>this.jobs.delete(id);advance(ms){const end=this.now+ms;let count=0;while(true){const first=[...this.jobs.entries()].filter(([,j])=>j.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!first)break;if(++count>20000)throw Error('unbounded test timers');this.jobs.delete(first[0]);this.now=first[1].at;first[1].f()}this.now=end;}}
function setup({pending=false,videoPending=false,unavailable=false,reject=false,limits={startup:30,capture:120,stall:1000}}={}){const clock=new Clock;let grant,playGrant,calls=0;const {A,ctx,Target}=load(FILE,{performance:{now:()=>clock.now},setTimeout:clock.set,clearTimeout:clock.clear,setInterval:clock.set,clearInterval:clock.clear,requestAnimationFrame:f=>clock.set(f,16),cancelAnimationFrame:clock.clear});
 const track=Object.assign(new Target,{readyState:'live',muted:false,stops:0,stop(){this.stops++;this.readyState='ended'}});
 const stream=Object.assign(new Target,{active:true,getTracks:()=>[track],getVideoTracks:()=>[track]});
 const video=Object.assign(new Target,{readyState:4,HAVE_ENOUGH_DATA:4,videoWidth:0,videoHeight:0,currentTime:0,srcObject:null,setAttribute(){},pause(){},play(){return videoPending?new Promise(r=>playGrant=r):Promise.resolve()}});
 ctx.navigator.mediaDevices=unavailable?undefined:{getUserMedia(){calls++;if(reject)return Promise.reject(new DOMException('no','NotAllowedError'));return pending?new Promise(r=>grant=r):Promise.resolve(stream)}};
 const states=[],errors=[];const c=new A.iv(video,()=>{},e=>errors.push(e),s=>states.push({...s}),limits);
 const start=()=>{const p=c.start();p.catch(()=>{});return p};return {A,ctx,clock,track,stream,video,c,start,states,errors,grant:()=>grant(stream),playGrant:()=>playGrant(),calls:()=>calls};}
async function test(name,fn){try{await fn();results.push({name,status:'passed'})}catch(e){results.push({name,status:'failed',error:e.stack})}}
(async()=>{
await test('R3 unanswered permission expires within startup deadline',async()=>{const h=setup({pending:true});h.start();assert.equal(h.c.phase,'awaiting-permission');h.clock.advance(30);assert.equal(h.c.phase,'failed');assert.equal(h.c.failure.code,'CAMERA_START_TIMEOUT');assert.equal(h.clock.jobs.size,0);assert.equal(h.errors.length,1)});
await test('R3 late permission after expiry closes tracks without revival',async()=>{const h=setup({pending:true});h.start();h.clock.advance(30);h.grant();await flush();assert.equal(h.track.stops,1);assert.equal(h.c.phase,'failed');assert.equal(h.video.srcObject,null);assert.equal(h.calls(),1)});
await test('R3 Stop before permission grant closes late stream',async()=>{const h=setup({pending:true});h.start();h.c.stop();h.grant();await flush();assert.equal(h.c.phase,'stopped');assert.equal(h.track.stops,1);assert.equal(h.clock.jobs.size,0)});
await test('R3 stalled playback shares the startup deadline',async()=>{const h=setup({videoPending:true});h.start();await flush();assert.equal(h.c.phase,'awaiting-video');h.clock.advance(30);assert.equal(h.c.phase,'failed');assert.equal(h.track.stops,1);h.playGrant();await flush();assert.equal(h.c.phase,'failed');assert.equal(h.clock.jobs.size,0)});
await test('R3 repeated Start returns same promise and never acquires twice',async()=>{const h=setup({pending:true});const p=h.start();assert.strictEqual(h.start(),p);assert.equal(h.calls(),1);h.c.stop();h.grant();await flush()});
await test('R3 cancellation wins against successful but unresolved play',async()=>{const h=setup({videoPending:true});h.start();await flush();h.c.stop();h.playGrant();await flush();assert.equal(h.track.stops,1);assert.equal(h.c.phase,'stopped');assert.equal(h.clock.jobs.size,0)});
for(const event of ['ended','inactive','error'])await test('R4 '+event+' immediately stops camera and releases resources',async()=>{const h=setup();h.start();await flush();assert.equal(h.c.phase,'scanning');(event==='ended'?h.track:event==='inactive'?h.stream:h.video).emit(event);assert.equal(h.c.phase,'failed');assert.equal(h.track.stops,1);assert.equal(h.video.srcObject,null);assert.equal(h.clock.jobs.size,0);assert.equal(h.errors.length,1)});
await test('R4 ended state without browser event is caught by health check',async()=>{const h=setup({limits:{startup:30,capture:5000,stall:1000}});h.start();await flush();h.track.readyState='ended';h.clock.advance(1000);assert.equal(h.c.failure.code,'CAMERA_ENDED');assert.equal(h.clock.jobs.size,0)});
await test('R4 inactive stream without event is caught',async()=>{const h=setup({limits:{startup:30,capture:5000,stall:1000}});h.start();await flush();h.stream.active=false;h.clock.advance(1000);assert.equal(h.c.failure.code,'CAMERA_ENDED')});
await test('R4 transient mute has bounded window and unmute resumes without reacquire',async()=>{const h=setup({limits:{startup:30,capture:5000,stall:1000}});h.start();await flush();h.track.emit('mute');assert.equal(h.c.phase,'stalled');h.clock.advance(400);h.track.emit('unmute');assert.equal(h.c.phase,'scanning');assert.equal(h.calls(),1);h.c.stop();assert.equal(h.clock.jobs.size,0)});
await test('R4 prolonged stall is terminal and cannot auto-restart',async()=>{const h=setup({limits:{startup:30,capture:5000,stall:1000}});h.start();await flush();h.video.emit('stalled');h.clock.advance(1000);assert.equal(h.c.failure.code,'CAMERA_STALLED');h.video.emit('playing');assert.equal(h.c.phase,'failed');assert.equal(h.calls(),1)});
await test('R4 missing new video frames is terminal even without stall events',async()=>{const h=setup({limits:{startup:30,capture:5000,stall:1000}});h.start();await flush();h.clock.advance(1000);assert.equal(h.c.failure.code,'CAMERA_STALLED')});
await test('R4 page hiding stops capture; return never silently restarts',async()=>{const h=setup();h.start();await flush();h.ctx.document.visibilityState='hidden';h.ctx.document.emit('visibilitychange');assert.equal(h.c.failure.code,'CAMERA_HIDDEN');h.ctx.document.visibilityState='visible';h.ctx.document.emit('visibilitychange');assert.equal(h.c.phase,'failed');assert.equal(h.calls(),1);assert.equal(h.clock.jobs.size,0)});
await test('R4 hiding while permission pending also closes late stream',async()=>{const h=setup({pending:true});h.start();h.ctx.document.visibilityState='hidden';h.ctx.document.emit('visibilitychange');h.grant();await flush();assert.equal(h.track.stops,1);assert.equal(h.c.failure.code,'CAMERA_HIDDEN')});
await test('capture deadline is independent of startup and remains terminal',async()=>{const h=setup();h.start();await flush();h.clock.advance(119);assert.equal(h.c.phase,'scanning');h.clock.advance(1);assert.equal(h.c.failure.code,'CAMERA_SCAN_TIMEOUT');const p=h.c.start();await assert.rejects(p,/explicitly/);assert.equal(h.calls(),1)});
await test('optional camera absence produces visible error without throwing beyond controller',async()=>{const h=setup({unavailable:true});await assert.rejects(h.start(),/unavailable/);assert.equal(h.c.failure.code,'CAMERA_UNAVAILABLE');assert.equal(h.clock.jobs.size,0)});
await test('permission rejection fails terminal with actionable message',async()=>{const h=setup({reject:true});await assert.rejects(h.start(),/denied/);assert.equal(h.c.phase,'failed');assert.equal(h.clock.jobs.size,0)});
await test('failed controller requires explicit rollback before new acquire',async()=>{const h=setup({pending:true});h.start();h.clock.advance(30);h.c.stop();assert.equal(h.c.phase,'failed');h.c.rollback();assert.equal(h.c.phase,'stopped');h.start();assert.equal(h.calls(),2);h.c.stop();h.grant();await flush()});
await test('cleanup is idempotent and listeners cannot revive operation',async()=>{const h=setup();h.start();await flush();h.c.stop();h.c.stop();h.c.stop();h.track.emit('ended');h.video.emit('playing');assert.equal(h.track.stops,1);assert.equal(h.c.phase,'stopped');assert.equal(h.clock.jobs.size,0);assert.equal([...Object.values(h.track.events)].reduce((n,s)=>n+s.size,0),0)});
const out={suite:'Camera lifecycle fault-injection contracts (mock clock/media, not hardware)',passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length,results};if(OUT)fs.writeFileSync(OUT,JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));process.exitCode=out.failed?1:0;
})().catch(e=>{console.error(e);process.exitCode=1});
