'use strict';
const fs=require('fs'),assert=require('assert/strict'),vm=require('vm'),crypto=require('crypto');
const {load}=require('./load.cjs');const FILE=process.argv[2],OUT=process.argv[3],{A,ctx}=load(FILE),rows=[];
const range=(process.env.TEST_RANGE||'1:999').split(':').map(Number);let index=0;
function app(){const a=A.Fv(),spec=A.Hp(),f=v=>({value:String(v),error:null});a.$refs={};a.$nextTick=async()=>{};
a.seed=f(spec.mnemonic);a.lockTime=f(spec.lockTime);a.psbtVersion=String(spec.psbtVersion);
a.inputs=spec.inputs.map((x,i)=>({id:i,utxoId:f(x.txid+':'+x.vout),amount:f(x.amountSats),pathSuffix:f(`${x.account}h/${x.change}/${x.addressIndex}`),sequence:f(x.sequence)}));
a.outputs=spec.outputs.map((x,i)=>({id:100+i,amount:f(x.amountSats),dest:f(`m/84h/0h/${x.dest.account}h/${x.dest.change}/${x.dest.addressIndex}`)}));a.recompute();return a;}

function state(a){return JSON.stringify([a.seed,a.stateSignature,a.psbtBase64,a.variants,a.walletSession,a.preparedRevision,a.sessionChecks,a.sessionHistory,a.guidedStatus,a.resultState,a.report?.name,a.signingPolicy,a.completedAt,a.scan.phase]);}
function modal(a,options={}){let runs=0;const original=a.runDemonstration.bind(a);a.runDemonstration=()=>{runs++;return original()};const d={open:false,showModal(){this.open=true;},close(){this.open=false;},...options};a.$refs.exampleDialog=d;a.$refs.exampleTitle={focus:o=>assert.equal(o.preventScroll,true)};return {d,runs:()=>runs};}
async function test(name,f){index++;if(index<range[0]||index>range[1])return;console.log('RUN',index,name);const start=performance.now();try{await f();rows.push({name,status:'passed',ms:Math.round(performance.now()-start)});}catch(e){rows.push({name,status:'failed',error:e.stack});}console.log(rows.at(-1).status,rows.at(-1).ms);fs.writeFileSync(OUT,JSON.stringify({complete:false,results:rows},null,2));}
(async()=>{
await test('CL-C01 one click uses existing published-example verifier, no active test mutation',()=>{const a=app(),m=modal(a),s=state(a);assert.equal(a.openExample(),true);assert(m.d.open);assert(a.demonstration.analysis.ok);assert(!a.demonstration.analysis.matched);assert.equal(a.demonstration.analysis.evidence.signaturesVerified,2);assert.equal(state(a),s);a.destroy();});
await test('CL-C02 repeated requests on open dialog do not reexecute or add results',()=>{const a=app(),m=modal(a),s=state(a);for(let i=0;i<10;i++)a.openExample();assert.equal(m.runs(),1);assert.equal(a.sessionSummary.checked,0);assert.equal(state(a),s);a.destroy();});
await test('CL-C03 closing and reopening uses recorded result without changing wallet',()=>{const a=app(),m=modal(a);a.openExample();const r=a.demonstration.analysis,s=state(a);m.d.close();a.openExample();assert.strictEqual(a.demonstration.analysis,r);assert.equal(state(a),s);a.destroy();});
await test('CL-C04 missing optional dialog is a reported no-op, not core failure',()=>{const a=app(),s=state(a);assert.equal(a.openExample(),false);assert.equal(a.demonstration.analysis,null);assert(a.notice.includes('unavailable'));assert.equal(state(a),s);a.destroy();});
await test('CL-C05 unavailable native dialog support does not evaluate the fixture',()=>{const a=app(),m=modal(a,{showModal:null}),s=state(a);assert.equal(a.openExample(),false);assert.equal(m.runs(),0);assert.equal(state(a),s);a.destroy();});
await test('CL-C06 failed dialog opening is explicit and preserves active test',()=>{const a=app(),m=modal(a,{showModal(){throw Error('dialog fault')}}),s=state(a);assert.equal(a.openExample(),false);assert.equal(m.runs(),0);assert(!m.d.open);assert(a.notice.includes('could not open'));assert.equal(state(a),s);a.destroy();});
await test('CL-C07 unexpected optional demo wrapper exception closes dialog without changing test',()=>{const a=app(),m=modal(a),s=state(a);a.runDemonstration=()=>{throw Error('injected')};assert.equal(a.openExample(),false);assert(!m.d.open);assert.equal(state(a),s);a.destroy();});
await test('CL-C08 known-example decoder exception is a visible demo error, not firmware finding',()=>{const a=app(),m=modal(a),s=state(a);vm.runInContext('globalThis.keepUp=Up;Up=()=>{throw Error("fixture failure")}',ctx);try{assert(a.openExample());assert(m.d.open);assert.equal(a.demonstration.analysis,null);assert(a.demonstration.error.includes('could not run'));assert.equal(state(a),s);}finally{vm.runInContext('Up=keepUp',ctx);a.destroy();}});
await test('CL-C09 unexpectedly matching attack fixture is not displayed as successful demo',()=>{const a=app();modal(a);const s=state(a);vm.runInContext('globalThis.keepUp=Up;Up=()=>({ok:true,matched:{},evidence:{signaturesVerified:2}})',ctx);try{a.openExample();assert.equal(a.demonstration.analysis,null);assert(a.demonstration.error.includes('expected result'));assert.equal(state(a),s);}finally{vm.runInContext('Up=keepUp',ctx);a.destroy();}});
await test('CL-C10 active camera blocks example without stopping or reacquiring it',()=>{const a=app(),m=modal(a);a.scan.active=true;a.scan.phase='scanning';const s=state(a);assert.equal(a.openExample(),false);assert.equal(m.runs(),0);assert(!m.d.open);assert.equal(a.scan.active,true);assert.equal(state(a),s);a.scan.active=false;a.destroy();});
await test('CL-C11 accepted result and full evidence remain immutable through example',()=>{const a=app();a.acknowledged=true;a.acceptArtifact(a.variants[0].txHex);const s=state(a),r=a.report(),e=a.exportEvidence();modal(a);a.openExample();assert.equal(state(a),s);assert.strictEqual(a.report(),r);assert.strictEqual(a.exportEvidence(),e);a.destroy();});
await test('CL-C12 incomplete finding remains incomplete after example',()=>{const a=app();a.acknowledged=true;a.acceptArtifact('not-a-response');const s=state(a);assert.equal(a.resultState,'incomplete');modal(a);a.openExample();assert.equal(state(a),s);assert.equal(a.resultState,'incomplete');a.destroy();});
await test('CL-C13 guided planned cases and policy unaffected by example',()=>{const a=app();a.sessionCount='3';a.startGuidedSession();const s=state(a);assert(a.guidedLocked);modal(a);a.openExample();assert.equal(state(a),s);assert.equal(a.guidedStatus.completed,0);a.destroy();});
await test('CL-C14 main result cannot export the example as a hardware result',()=>{const a=app();modal(a);a.openExample();assert.equal(a.resultState,'unverified');assert.equal(a.hasEvidence,false);assert.throws(()=>a.report());assert.throws(()=>a.exportEvidence());a.destroy();});
await test('CL-C15 workspace uses preventScroll focus without scrolling callback',async()=>{const a=app(),seen=[];a.$refs.advancedTitle={focus:o=>seen.push(o)};a.focusSection=()=>{throw Error('must not scroll')};const s=state(a);await a.openWorkspace('advanced');assert.equal(seen.length,1);assert.equal(seen[0].preventScroll,true);assert.equal(state(a),s);a.destroy();});
await test('CL-C16 late workspace completion cannot focus an earlier view',async()=>{const a=app(),queue=[],hits=[];a.$nextTick=()=>new Promise(resolve=>queue.push(resolve));a.$refs.advancedTitle={focus:()=>hits.push('advanced')};a.$refs.sessionTitle={focus:()=>hits.push('session')};const first=a.openWorkspace('advanced'),last=a.openWorkspace('session');queue.splice(0).forEach(f=>f());await Promise.all([first,last]);assert.deepEqual(hits,['session']);a.destroy();});
await test('CL-C17 epoch invalidation cancels pending workspace focus',async()=>{const a=app(),queue=[],hits=[];a.$nextTick=()=>new Promise(resolve=>queue.push(resolve));a.$refs.sessionTitle={focus:()=>hits.push('session')};const action=a.openWorkspace('session');a.epoch++;queue.splice(0).forEach(f=>f());assert.equal(await action,false);assert.equal(hits.length,0);a.destroy();});
await test('CL-C18 same-length fresh-wallet operation remains authoritative',()=>{const a=app(),seed=a.seed.value;a.randomizeAll();assert.notEqual(a.seed.value,seed);assert.equal(a.wordCount,'12');assert.equal(a.sessionSummary.checked,0);assert.equal(a.acknowledged,false);a.destroy();});
await test('CL-C19 guided wallet replacement remains blocked',()=>{const a=app();a.sessionCount='2';a.startGuidedSession();const s=state(a);a.randomizeAll();assert.equal(state(a),s);assert(a.notice.includes('end the session'));a.destroy();});
await test('CL-C20 switching word length still creates fresh words and resets acknowledgment',()=>{const a=app();a.acknowledged=true;const s=a.seed.value;a.selectSeedLength(24);assert.notEqual(a.seed.value,s);assert.equal(a.seed.value.split(' ').length,24);assert.equal(a.acknowledged,false);a.destroy();});
const out={suite:'Clarity navigation and isolated-example contracts/faults',complete:true,totalDefined:index,testRange:range,passed:rows.filter(x=>x.status==='passed').length,failed:rows.filter(x=>x.status==='failed').length,sha256:crypto.createHash('sha256').update(fs.readFileSync(FILE)).digest('hex'),results:rows};fs.writeFileSync(OUT,JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));process.exitCode=out.failed?1:0;
})().catch(e=>{console.error(e);process.exitCode=1});
