'use strict';
// Actual candidate navigation contracts; no renderer, device or camera-origin claims.
const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto');
const {load}=require('./load.cjs');const FILE=process.argv[2],OUT=process.argv[3],{A}=load(FILE),rows=[];
const range=(process.env.TEST_RANGE||'1:999').split(':').map(Number);let index=0;
function app(){const a=A.Fv(),s=A.Hp(),f=v=>({value:String(v),error:null});a.$refs={};a.$nextTick=async()=>{};
 a.seed=f(s.mnemonic);a.lockTime=f(s.lockTime);a.psbtVersion=String(s.psbtVersion);
 a.inputs=s.inputs.map((x,i)=>({id:i,utxoId:f(x.txid+':'+x.vout),amount:f(x.amountSats),pathSuffix:f(`${x.account}h/${x.change}/${x.addressIndex}`),sequence:f(x.sequence)}));
 a.outputs=s.outputs.map((x,i)=>({id:100+i,amount:f(x.amountSats),dest:f(`m/84h/0h/${x.dest.account}h/${x.dest.change}/${x.dest.addressIndex}`)}));a.recompute();return a;}
function core(a){return JSON.stringify([a.seed,a.stateSignature,a.psbtBase64,a.variants,a.walletSession,a.preparedRevision,a.sessionChecks,a.sessionHistory,a.guidedStatus,a.resultState,a.completedAt,a.signingPolicy,a.artifactText]);}
function refs(a){const hits=[];for(const name of ['prepareTitle','signTitle','intakeSection','resultTitle','advancedTitle','sessionTitle'])a.$refs[name]={focus:o=>hits.push(['focus',name,o.preventScroll]),scrollIntoView:o=>hits.push(['scroll',name])};return hits;}
async function tick(){await Promise.resolve();await Promise.resolve();}
async function test(name,fn){index++;if(index<range[0]||index>range[1])return;const t=performance.now();try{await fn();rows.push({name,status:'passed',ms:Math.round(performance.now()-t)});}catch(e){rows.push({name,status:'failed',error:e.stack});}fs.writeFileSync(OUT,JSON.stringify({complete:false,results:rows},null,2));console.log(index,rows.at(-1).status,name);}
(async()=>{
await test('D-C01 unacknowledged step entry rejected without altering core state',()=>{const a=app(),s=core(a);assert.equal(a.goToStep(3),false);assert.equal(a.step,1);assert.equal(a.acknowledged,false);assert.equal(core(a),s);a.destroy();});
await test('D-C02 invalid navigation indices rejected',()=>{const a=app(),s=core(a);for(const n of [0,4,'3',NaN,null])assert.throws(()=>a.goToStep(n));assert.equal(core(a),s);a.destroy();});
await test('D-C03 left navigation preserves core and requests focus without scrolling',async()=>{const a=app();a.acknowledged=true;const hits=refs(a),s=core(a);assert(a.goToStep(2));await tick();assert.deepEqual(hits,[['focus','signTitle',true]]);assert.equal(core(a),s);a.destroy();});
await test('D-C04 unverified Results reopens intake without a signing or camera operation',async()=>{const a=app();a.acknowledged=true;const hits=refs(a),s=core(a);a.startScan=()=>{throw Error('camera invoked')};a.verify=()=>{throw Error('verification invoked')};assert(a.goToStep(3));await tick();assert(a.intakeOpen);assert.equal(core(a),s);assert.equal(hits.filter(x=>x[0]==='scroll').length,0);a.destroy();});
await test('D-C05 incomplete import and original error persist across Results reentry',()=>{const a=app();a.acknowledged=true;a.acceptArtifact('not-a-response');const r=a.report(),s=core(a);a.goToStep(1);a.goToStep(3);assert(a.intakeOpen);assert.equal(a.resultState,'incomplete');assert.strictEqual(a.report(),r);assert.equal(core(a),s);a.destroy();});
await test('D-C06 completed match remains read-only and original evidence object unchanged',()=>{const a=app();a.acknowledged=true;a.acceptArtifact(a.variants[0].txHex);const r=a.report(),e=a.exportEvidence(),s=core(a);a.goToStep(1);a.goToStep(3);assert.equal(a.intakeOpen,false);assert(a.isTestComplete);assert.strictEqual(a.report(),r);assert.strictEqual(a.exportEvidence(),e);assert.equal(core(a),s);a.destroy();});
await test('D-C07 reselecting live Results leaves capture untouched',()=>{const a=app();a.acknowledged=true;a.step=3;a.scan.active=true;a.scan.phase='scanning';a.scan.progress=.4;let stops=0;a.stopScan=()=>{stops++};const s=core(a),capture=JSON.stringify(a.scan);for(let i=0;i<10;i++)assert(a.goToStep(3));assert.equal(stops,0);assert.equal(JSON.stringify(a.scan),capture);assert.equal(core(a),s);a.destroy();});
await test('D-C08 reselecting Results during permission wait does not cancel startup',()=>{const a=app();a.acknowledged=true;a.step=3;a.scan.active=true;a.scan.phase='awaiting-permission';let stopped=0;a.stopScan=()=>{stopped++};a.goToStep(3);assert.equal(stopped,0);assert.equal(a.scan.phase,'awaiting-permission');a.destroy();});
await test('D-C09 leaving active Results explicitly stops capture once',()=>{const a=app();a.acknowledged=true;a.step=3;a.scan.active=true;a.scan.phase='scanning';let stops=0;const original=a.stopScan.bind(a);a.stopScan=()=>{stops++;original()};a.goToStep(2);assert.equal(stops,1);assert.equal(a.scan.active,false);assert.equal(a.scan.phase,'stopped');assert.equal(a.step,2);a.destroy();});
await test('D-C10 navigating does not clear a failed camera state or error',()=>{const a=app();a.acknowledged=true;a.scan.phase='failed';a.scan.error='retained capture failure';a.scan.code='CAMERA_ENDED';for(const n of [1,2,3])a.goToStep(n);assert.equal(a.scan.phase,'failed');assert.equal(a.scan.error,'retained capture failure');assert.equal(a.scan.code,'CAMERA_ENDED');assert(a.intakeOpen);a.destroy();});
await test('D-C11 late step focus cannot override newer step navigation',async()=>{const a=app();a.acknowledged=true;const queue=[],hits=refs(a);a.$nextTick=()=>new Promise(r=>queue.push(r));a.goToStep(2);a.goToStep(3);queue.splice(0).forEach(f=>f());await tick();assert.deepEqual(hits,[['focus','intakeSection',true]]);a.destroy();});
await test('D-C12 epoch change cancels deferred navigation focus',async()=>{const a=app();a.acknowledged=true;const queue=[],hits=refs(a);a.$nextTick=()=>new Promise(r=>queue.push(r));a.goToStep(2);a.epoch++;queue.splice(0).forEach(f=>f());await tick();assert.deepEqual(hits,[]);a.destroy();});
await test('D-C13 workspace change invalidates pending step focus',async()=>{const a=app();a.acknowledged=true;const queue=[],hits=refs(a);a.$nextTick=()=>new Promise(r=>queue.push(r));a.goToStep(2);const p=a.openWorkspace('session');queue.splice(0).forEach(f=>f());await p;await tick();assert.deepEqual(hits,[['focus','sessionTitle',true]]);a.destroy();});
await test('D-C14 step selection invalidates pending workspace focus',async()=>{const a=app();a.acknowledged=true;const queue=[],hits=refs(a);a.$nextTick=()=>new Promise(r=>queue.push(r));const p=a.openWorkspace('advanced');a.goToStep(3);queue.splice(0).forEach(f=>f());await p;await tick();assert.deepEqual(hits,[['focus','intakeSection',true]]);assert.equal(a.workspaceView,'test');a.destroy();});
await test('D-C15 primary acknowledgement deliberately reveals transaction review',async()=>{const a=app(),hits=refs(a),s=core(a);a.confirmWalletLoaded();await tick();assert(a.acknowledged);assert.equal(a.step,2);assert.deepEqual(hits,[['focus','signTitle',true],['scroll','signTitle']]);assert.equal(core(a),s);a.destroy();});
await test('D-C16 invalid wallet cannot become acknowledged by its primary action',()=>{const a=app();a.seed={value:'invalid wallet',error:null};a.invalidate();a.recompute();assert(a.buildProblem);a.confirmWalletLoaded();assert.equal(a.acknowledged,false);assert.equal(a.step,1);assert(a.notice);a.destroy();});
await test('D-C17 invalid transaction blocks step change and produces explicit notice',()=>{const a=app();a.acknowledged=true;a.lockTime.value='not-an-integer';a.invalidate();assert.equal(a.goToStep(2),false);assert.equal(a.step,1);assert(a.buildProblem);assert.equal(a.notice,a.buildProblem);a.destroy();});
await test('D-C18 guided failure remains halted after reopening intake',()=>{const a=app();a.sessionCount='2';a.startGuidedSession();a.acknowledged=true;a.acceptArtifact('bad data');assert.equal(a.guidedStatus.phase,'halted');const s=core(a),r=a.exportSessionReport();a.goToStep(1);a.goToStep(3);assert(a.intakeOpen);assert.equal(a.guidedStatus.canReceive,false);assert.equal(a.guidedStatus.canAdvance,false);assert.equal(core(a),s);assert.equal(JSON.stringify(a.exportSessionReport()),JSON.stringify(r));a.destroy();});
await test('D-C19 mismatch result and journal stay immutable during navigation',()=>{const a=app();a.acknowledged=true;a.acceptArtifact(A.Vp);assert.equal(a.resultState,'mismatch');const s=core(a),r=a.report();a.goToStep(2);a.goToStep(3);assert.equal(core(a),s);assert.strictEqual(a.report(),r);assert.equal(a.intakeOpen,false);a.destroy();});
await test('D-C20 existing paste draft stays unchanged across step selection',()=>{const a=app();a.acknowledged=true;a.artifactText='unfinished paste';a.pasteOpen=true;const s=core(a);a.goToStep(1);a.goToStep(3);assert.equal(core(a),s);assert(a.pasteOpen);assert(a.intakeOpen);a.destroy();});
await test('D-C21 repeated idle Results selections cannot create counts or camera calls',async()=>{const a=app();a.acknowledged=true;a.startScan=()=>{throw Error('unexpected camera')};const s=core(a);for(let i=0;i<20;i++)a.goToStep(3);await tick();assert.equal(core(a),s);assert.equal(a.sessionSummary.checked,0);a.destroy();});
await test('D-C22 unavailable focus nodes do not alter or crash navigation',async()=>{const a=app();a.acknowledged=true;const s=core(a);a.$refs={};a.goToStep(3);await tick();assert.equal(core(a),s);assert(a.intakeOpen);a.destroy();});
await test('D-C23 example remains isolated after renamed entry and navigation',()=>{const a=app();a.acknowledged=true;a.goToStep(3);const s=core(a);a.$refs.exampleDialog={open:false,showModal(){this.open=true},close(){this.open=false}};assert(a.openExample());assert(a.demonstration.analysis.ok);assert(!a.demonstration.analysis.matched);assert.equal(core(a),s);assert.equal(a.sessionSummary.checked,0);a.destroy();});
await test('D-C24 completed acknowledgement is a no-op rather than advancing or resetting',()=>{const a=app();a.acknowledged=true;a.acceptArtifact(a.variants[0].txHex);const s=core(a),step=a.step;a.confirmWalletLoaded();assert.equal(core(a),s);assert.equal(a.step,step);a.destroy();});
const out={suite:'Delivery step-navigation contracts/faults',complete:true,totalDefined:index,testRange:range,sha256:crypto.createHash('sha256').update(fs.readFileSync(FILE)).digest('hex'),passed:rows.filter(x=>x.status==='passed').length,failed:rows.filter(x=>x.status==='failed').length,results:rows};fs.writeFileSync(OUT,JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));process.exitCode=out.failed?1:0;
})().catch(e=>{console.error(e);process.exitCode=1});
