'use strict';
// Tests use public disposable fixtures and the exact candidate module. No physical device.
const {load}=require('./load.cjs'),fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto');
const FILE=process.argv[2],OUT=process.argv[3],{A,ctx}=load(FILE),rows=[];
const range=(process.env.TEST_RANGE||'1:999').split(':').map(Number);let count=0;
const state=a=>JSON.stringify([a.stateSignature,a.walletSession,a.wordCount,a.epoch,a.testNumber,a.acknowledged,a.sessionHistory,a.guidedStatus,a.resultState,a.scan,a.preparedRevision]);
function app(){let a=A.Fv();a.$refs={};a.$nextTick=async()=>{};a.recompute();return a;}
function confirmation(a,over={}){let d={open:false,isConnected:true,scrollTop:23,showModal(){this.open=true},close(){this.open=false},...over};a.$refs.walletChangeDialog=d;a.$refs.keepWallet={focus:o=>assert(o.preventScroll)};return d;}
function used(){let a=app();a.acknowledged=true;confirmation(a);return a;}
function completed(){let a=used();a.acceptArtifact(a.variants[0].txHex);assert.equal(a.resultState,'match');return a;}
function begin(a,n=2){a.sessionCount=String(n);a.startGuidedSession();assert(a.guidedLocked);return a;}
function dispose(a){a.destroy()}
async function test(name,f){count++;if(count<range[0]||count>range[1])return;let t=performance.now();console.log('RUN',count,name);try{await f();rows.push({name,status:'passed',ms:Math.round(performance.now()-t)})}catch(e){rows.push({name,status:'failed',error:e.stack})}fs.writeFileSync(OUT,JSON.stringify({complete:false,results:rows},null,2));console.log(rows.at(-1).status)}
(async()=>{
await test('FB-C01 example checks actual recorded bytes without wallet/signature-result substitution',()=>{const a=app(),before=state(a);a.$refs.exampleDialog={open:false,showModal(){this.open=true},close(){this.open=false}};a.openExample();assert(a.demonstration.analysis.ok);assert(!a.demonstration.analysis.matched);assert.equal(a.demonstration.analysis.evidence.signaturesVerified,2);assert.equal(a.demonstration.analysis.evidence.transactionId,A.Cp(a.demonstration.analysis.txHex));assert.equal(state(a),before);dispose(a)});
await test('FB-C02 reopen and repeated-open reset example scroll without recalculating active test',()=>{const a=app(),d={open:false,scrollTop:999,showModal(){this.open=true},close(){this.open=false}};a.$refs.exampleDialog=d;a.openExample();let report=a.demonstration.analysis,before=state(a);d.scrollTop=999;a.openExample();assert.equal(d.scrollTop,0);d.close();d.scrollTop=999;a.openExample();assert.equal(d.scrollTop,0);assert.strictEqual(a.demonstration.analysis,report);assert.equal(state(a),before);dispose(a)});
await test('FB-C03 missing optional example is explicit and does not change live test',()=>{let a=app(),s=state(a);assert.equal(a.openExample(),false);assert.match(a.notice,/unavailable/);assert.equal(state(a),s);dispose(a)});
await test('FB-C04 unused wallet replacement keeps chosen word count with one fresh identity',()=>{let a=app(),prev=a.walletSession;assert(a.requestWalletChange());assert.notEqual(a.walletSession,prev);assert.equal(a.wordCount,'12');assert.equal(a.testNumber,1);assert(!a.walletChangePending);dispose(a)});
await test('FB-C05 unused word selector changes once and current selection is a no-op',()=>{let a=app(),s=state(a);assert.equal(a.requestWalletChange(12,false),false);assert.equal(state(a),s);assert(a.requestWalletChange(24,false));assert.equal(a.seed.value.split(' ').length,24);assert.equal(a.wordCount,'24');dispose(a)});
await test('FB-C06 used wallet opens confirmation with no state mutation',()=>{let a=used(),s=state(a);assert(a.requestWalletChange());assert(a.walletChangePending);assert(a.$refs.walletChangeDialog.open);assert.equal(state(a),s);dispose(a)});
await test('FB-C07 cancel used-wallet replacement preserves pending transaction and seed',()=>{let a=used(),s=state(a);a.requestWalletChange(24);a.cancelWalletChange();assert(!a.walletChangePending);assert(!a.$refs.walletChangeDialog.open);assert.equal(state(a),s);assert.equal(a.confirmWalletChange(),false);dispose(a)});
await test('FB-C08 confirmation preserves target word count and consumes the request exactly once',()=>{let a=used(),prev=a.walletSession;a.requestWalletChange(24,false);assert(a.confirmWalletChange());assert.notEqual(a.walletSession,prev);assert.equal(a.wordCount,'24');assert(!a.acknowledged);let s=state(a);assert.equal(a.confirmWalletChange(),false);assert.equal(state(a),s);dispose(a)});
await test('FB-C09 completed result and evidence remain immutable until explicit replacement',()=>{let a=completed(),s=state(a),report=a.report();a.requestWalletChange();assert.deepEqual(a.report(),report);assert.equal(state(a),s);a.cancelWalletChange();assert.deepEqual(a.report(),report);dispose(a)});
await test('FB-C10 explicit replacement resets current result/history and creates a fresh unacknowledged wallet',()=>{let a=completed();a.requestWalletChange();assert(a.confirmWalletChange());assert.equal(a.resultState,'unverified');assert.equal(a.sessionHistory.length,0);assert.equal(a.sessionSummary.checked,0);assert.equal(a.step,1);assert.equal(a.workspaceView,'test');assert(!a.acknowledged);dispose(a)});
await test('FB-C11 used word-count change cannot discard a completed response without confirmation',()=>{let a=completed(),s=state(a);a.requestWalletChange(24,false);assert.equal(state(a),s);assert.equal(a.wordCount,'12');a.cancelWalletChange();assert.equal(state(a),s);dispose(a)});
await test('FB-C12 concurrent replacement requests cannot overwrite the first authorized intent',()=>{let a=used();assert(a.requestWalletChange(24));assert.equal(a.requestWalletChange(12),false);assert.equal(a.walletChangeWords,24);assert(a.confirmWalletChange());assert.equal(a.wordCount,'24');dispose(a)});
for(const [name,mutate] of [
 ['wallet',a=>{a.walletSession='changed'}],['epoch',a=>{a.epoch++}],['transaction',a=>{a.outputs[0].amount.value='1'}],
 ['result revision',a=>{a.resultRevision++}],['session revision',a=>{a.sessionRevision++}],['file completion',a=>{a.fileRequest++}],
 ['word count',a=>{a.wordCount='24'}],['signing policy',a=>{a.signingPolicy='plain'}]
])await test('FB-C13 stale confirmation rejects changed '+name,()=>{let a=used();a.requestWalletChange();mutate(a);let s=state(a);assert.equal(a.confirmWalletChange(),false);assert.equal(state(a),s);assert(!a.walletChangePending);assert.match(a.notice,/changed/);dispose(a)});
await test('FB-C14 active guided session cannot request a new wallet or change word length',()=>{let a=begin(app()),s=state(a);assert.equal(a.requestWalletChange(),false);assert.equal(a.requestWalletChange(24,false),false);assert.equal(state(a),s);assert.match(a.notice,/End the guided session/);dispose(a)});
await test('FB-C15 guided session started after confirmation invalidates replacement',()=>{let a=used();a.requestWalletChange();begin(a);let s=state(a);assert.equal(a.confirmWalletChange(),false);assert.equal(state(a),s);dispose(a)});
await test('FB-C16 active capture is not hidden or reacquired by replacement',()=>{let a=used();a.scan.active=true;let s=state(a);assert.equal(a.requestWalletChange(),false);assert.equal(state(a),s);assert.match(a.notice,/Stop the camera/);a.scan.active=false;dispose(a)});
await test('FB-C17 capture beginning after prompt rejects replacement and leaves capture untouched',()=>{let a=used();a.requestWalletChange();a.scan.active=true;let s=state(a);assert.equal(a.confirmWalletChange(),false);assert.equal(state(a),s);a.scan.active=false;dispose(a)});
for(const [name,over] of [['missing',null],['unsupported',{showModal:undefined}],['disconnected',{isConnected:false}],['throws',{showModal(){throw Error('injected')}}]])await test('FB-C18 unavailable confirmation fails closed: '+name,()=>{let a=used();if(over===null)delete a.$refs.walletChangeDialog;else confirmation(a,over);let s=state(a);assert.equal(a.requestWalletChange(),false);assert.equal(state(a),s);assert(!a.walletChangePending);assert.match(a.notice,/confirmation/);dispose(a)});
await test('FB-C19 entropy failure after confirmation preserves existing result without retry',()=>{let a=completed();a.requestWalletChange();let s=state(a),old=ctx.crypto;ctx.crypto={getRandomValues(){throw Error('injected entropy failure')}};try{assert.equal(a.confirmWalletChange(),false)}finally{ctx.crypto=old}assert.equal(state(a),s);assert.match(a.notice,/Could not generate/);assert(!a.walletChangePending);dispose(a)});
await test('FB-C20 page pause cancels pending replacement instead of resuming stale intent',()=>{let a=used();a.requestWalletChange();let seed=a.seed.value;a.pause();assert(!a.walletChangePending);assert(!a.$refs.walletChangeDialog.open);assert.equal(a.confirmWalletChange(),false);assert.equal(a.seed.value,seed);dispose(a)});
await test('FB-C21 existing exports are reused before replacement and do not consume intent',()=>{let a=completed(),s=state(a),calls=[];a.downloadResult=()=>calls.push('result');a.downloadHistory=()=>calls.push('session');a.requestWalletChange();assert(a.saveBeforeWalletChange('result'));assert(a.saveBeforeWalletChange('session'));assert.deepEqual(calls,['result','session']);assert.equal(state(a),s);assert(a.walletChangePending);dispose(a)});
await test('FB-C22 blocked export displays failure while preserving wallet and pending intent',()=>{let a=completed(),s=state(a);a.requestWalletChange();a.downloadResult=()=>{a.notice='Download blocked'};assert.equal(a.saveBeforeWalletChange('result'),false);assert.equal(a.walletChangeError,'Download blocked');assert.equal(state(a),s);assert(a.walletChangePending);a.downloadHistory=()=>{throw Error('blocked')};assert.equal(a.saveBeforeWalletChange('session'),false);assert.match(a.walletChangeError,/Keep this wallet/);assert.equal(state(a),s);dispose(a)});
await test('FB-C23 ended session remains exportable and requires confirmation before disposal',()=>{let a=begin(app(),30);a.endGuidedSession();let r=a.exportSessionReport(),s=state(a);confirmation(a);assert(a.requestWalletChange());assert.equal(state(a),s);assert.deepEqual(a.exportSessionReport(),r);assert.equal(r.status.notCompleted,30);a.cancelWalletChange();assert.deepEqual(a.exportSessionReport(),r);dispose(a)});
await test('FB-C24 ordinary operator end is neutral, not a verification failure',()=>{let a=begin(app());a.endGuidedSession();let row=a.sessionHistory.at(-1);assert.equal(a.historyTone(row),'ended');assert.equal(a.recordedOperationFailureCount,0);assert.equal(a.recordedIncompleteCount,0);assert.equal(a.sessionSummary.checked,0);dispose(a)});
await test('FB-C25 halted control finding remains after ending and is not disguised as normal stop',()=>{let a=begin(app());a.signingPolicy='plain';assert.equal(a.checkGuidedBinding(),false);a.endGuidedSession();assert.equal(a.recordedOperationFailureCount,1);assert.equal(a.historyTone(a.sessionHistory.at(-1)),'incomplete');assert.equal(a.exportHistory().events.filter(x=>x.type==='control-error').length,1);dispose(a)});
await test('FB-C26 repeated end does not duplicate history or counts',()=>{let a=begin(app());a.endGuidedSession();let r=a.exportSessionReport(),s=state(a);a.endGuidedSession();assert.equal(state(a),s);assert.deepEqual(a.exportSessionReport(),r);dispose(a)});
await test('FB-C27 invalid confirmation inputs reject without changing state',()=>{let a=used(),s=state(a);for(let w of [0,13,'24',NaN,Infinity,null])assert.throws(()=>a.requestWalletChange(w),/Choose/);assert.equal(a.confirmWalletChange(),false);assert.equal(a.saveBeforeWalletChange('result'),false);assert.equal(state(a),s);dispose(a)});
const r={suite:'Feedback visibility and wallet-intent contracts/faults',complete:true,total_defined:count,test_range:range.join(':'),sha256:crypto.createHash('sha256').update(fs.readFileSync(FILE)).digest('hex'),passed:rows.filter(x=>x.status==='passed').length,failed:rows.filter(x=>x.status==='failed').length,results:rows};fs.writeFileSync(OUT,JSON.stringify(r,null,2));console.log(JSON.stringify({...r,results:undefined}));process.exitCode=r.failed?1:0;
})();
