'use strict';
// Exercise the real isolated demo and fault paths. No physical signer substitute.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto'),{load}=require('./load.cjs');
const FILE=process.argv[2],OUT=process.argv[3],{A,ctx}=load(FILE),results=[];
function test(name,f){try{f();results.push({name,status:'passed'})}catch(e){results.push({name,status:'failed',error:e.stack})}}
function app(){const a=A.Fv();a.$refs={};a.$nextTick=async()=>{};a.recompute();return a}
function state(a){return JSON.stringify([a.seed,a.walletSession,a.stateSignature,a.psbtBase64,a.variants,a.sessionChecks,a.signingPolicy,a.guidedStatus,a.resultState,a.completedAt,a.inspect()]);}
function fault(replacement,check){vm.runInContext('globalThis.originalUp=Up;Up='+replacement,ctx);try{check()}finally{vm.runInContext('Up=originalUp',ctx)}}
test('O-D01 demo is not run at startup and does not gate a prepared test',()=>{const a=app();assert.equal(a.demonstration.analysis,null);assert.equal(a.demonstration.error,'');assert(a.transactionReady);a.destroy()});
test('O-D02 published example gives two valid but nonmatching signatures',()=>{const x=A.Up();assert(x.ok);assert(!x.matched);assert.equal(x.evidence.signaturesVerified,2)});
test('O-D03 example preserves the current wallet, transaction, policy and journal',()=>{const a=app(),s=state(a);a.runDemonstration();assert(a.demonstration.analysis.ok);assert.equal(state(a),s);a.destroy()});
test('O-D04 repeated explicit demo does not duplicate session progress',()=>{const a=app();a.runDemonstration();const d=a.demonstration.analysis,s=state(a);for(let i=0;i<5;i++)a.runDemonstration();assert.strictEqual(a.demonstration.analysis,d);assert.equal(state(a),s);assert.equal(a.sessionSummary.checked,0);a.destroy()});
test('O-D05 demo cannot replace a completed user result or its evidence',()=>{const a=app();a.acknowledged=true;a.acceptArtifact(a.variants[0].txHex);const s=state(a),report=a.report(),evidence=JSON.stringify(a.exportEvidence());a.runDemonstration();assert.equal(state(a),s);assert.strictEqual(a.report(),report);assert.equal(JSON.stringify(a.exportEvidence()),evidence);a.destroy()});
test('O-D06 thrown optional demo error leaves main test usable until explicit demo retry',()=>{const a=app(),s=state(a);fault('()=>{throw Error("injected optional failure")}',()=>a.runDemonstration());assert(a.demonstration.error);assert.equal(a.demonstration.analysis,null);assert.equal(state(a),s);a.runDemonstration();assert(a.demonstration.analysis.ok);assert.equal(a.demonstration.error,'');a.destroy()});
for(const [label,replacement] of [['unexpected match','()=>({ok:true,matched:{},evidence:{signaturesVerified:2}})'],['wrong count','()=>({ok:true,matched:null,evidence:{signaturesVerified:1}})'],['incomplete','()=>({ok:false})']])test('O-D07 wrong example outcome is visibly rejected: '+label,()=>{const a=app(),s=state(a);fault(replacement,()=>a.runDemonstration());assert(a.demonstration.error);assert.equal(a.demonstration.analysis,null);assert.equal(state(a),s);a.destroy()});
test('O-D08 demo absence/failure never creates a firmware qualification',()=>{const a=app();fault('undefined',()=>a.runDemonstration());assert(a.demonstration.error);a.acknowledged=true;a.acceptArtifact(a.variants[0].txHex);const r=a.report();assert.equal(r.result,'match');assert.equal(r.firmwareInspected,false);assert.equal(r.deviceOrigin,'not-attested');assert.equal(a.sessionSummary.checked,1);a.destroy()});
const out={suite:'Optional demo isolation and negative contracts',complete:true,sha256:crypto.createHash('sha256').update(fs.readFileSync(FILE)).digest('hex'),passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length,results};fs.writeFileSync(OUT,JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));process.exitCode=out.failed?1:0;
