'use strict';
const fs=require('fs'),assert=require('assert/strict'),{load}=require('./load.cjs');
const FILE=process.argv[2],OUT=process.argv[3],{A,ctx}=load(FILE);const results=[];let testIndex=0;const range=(process.env.TEST_RANGE||'1:999').split(':').map(Number);
function test(name,fn){testIndex++;if(testIndex<range[0]||testIndex>range[1])return;console.log("RUN",testIndex,name);let start=performance.now();try{fn();results.push({name,status:'passed',ms:+(performance.now()-start).toFixed(2)});console.log('DONE',testIndex,Math.round(performance.now()-start));}catch(e){results.push({name,status:'failed',error:e.stack});}}
const hex=b=>A.K.encode(b), bytes=t=>A.K.decode(t);
const spec=A.Hp(),root=A.up(spec.mnemonic),refs=A.Np(spec,root),tx=refs[0].txHex,psbt=A.Tp(spec,root),raw=bytes(tx);
function signed(version=2){const p=A.wp({...spec,psbtVersion:version},root),r=A.ap.fromRaw(raw,{allowUnknownInputs:true,allowUnknownOutputs:true,disableScriptCheck:true});for(let i=0;i<spec.inputs.length;i++){const w=r.getInput(i).finalScriptWitness;p.updateInput(i,{partialSig:[[w[1],w[0]]]},true);}return p;}
function check(p,version=2){return A.zp({...spec,psbtVersion:version},{kind:'psbt',bytes:p.toPSBT(version)},refs,root)}
function mutate(frame,fn){const parts=frame.split('/'),BW=A.__().default,part=A.g_().FountainEncoderPart.fromCBOR(BW.decode(parts[2],BW.STYLES.MINIMAL));fn(part);return A.x_.UREncoder.encodePart(parts[0].slice(3),part)}
const frames=A.w_(raw,90),bw=A.__().default;
function rejected(fn,pattern){assert.throws(fn,pattern)}
function app(){const a=A.Fv();a.$refs={};a.$nextTick=async()=>{};a.seed={value:spec.mnemonic,error:null};a.lockTime={value:String(spec.lockTime),error:null};a.psbtVersion='2';const f=v=>({value:String(v),error:null});a.inputs=spec.inputs.map((v,i)=>({id:i,utxoId:f(v.txid+':'+v.vout),amount:f(v.amountSats),pathSuffix:f(v.account+'h/'+v.change+'/'+v.addressIndex),sequence:f(v.sequence)}));a.outputs=spec.outputs.map((v,i)=>({id:50+i,amount:f(v.amountSats),dest:f('m/84h/0h/0h/0/18')}));a.acknowledged=true;a.recompute();assert.equal(a.buildProblem,'');return a;}
test('R1 checksum failure is terminal; originals cannot revive it; explicit new session succeeds',()=>{const s=new A.E_(),bad=frames.map((f,i)=>i===0?mutate(f,p=>p._fragment[3]^=1):f);rejected(()=>bad.forEach(f=>s.feed(f)),/checksum/);assert(s.status().failed);assert.equal(s.status().progress,0);assert.equal(s.result,null);rejected(()=>s.feed(frames[0]),/failed/);s.rollback();frames.forEach(f=>s.feed(f));assert.equal(hex(s.verify().bytes),tx)});
for(const [name,tail] of [['junk','garbage'],['mixed family','p1of1 AA=='],['another single transfer','ur:bytes/'+bw.encode(A.K.encode(A.S_(Uint8Array.of(1))),bw.STYLES.MINIMAL)],['conflicting duplicate',mutate(frames[0],p=>p._fragment[3]^=1)]])test('R2 finite UR rejects trailing '+name,()=>rejected(()=>A.Pv(frames.join('\n')+'\n'+tail)));
test('R2 finite UR accepts identical duplicate parts before and after completion',()=>assert.equal(hex(A.Pv([...frames,frames[0],frames[2]].join('\n')).bytes),tx));
test('R2 redundant fountain equations accepted after completion',()=>{const enc=new A.x_.UREncoder(new A.x_.UR(Buffer.from(A.S_(raw)),'crypto-psbt'),90);const parts=[];for(let i=0;i<enc.fragmentsLength+12;i++)parts.push(enc.nextPart());assert.equal(hex(A.Pv(parts.join('\n')).bytes),tx)});
test('R2 false redundant fountain equation rejected after completion',()=>{const enc=new A.x_.UREncoder(new A.x_.UR(Buffer.from(A.S_(raw)),'crypto-psbt'),90);const parts=[];for(let i=0;i<enc.fragmentsLength+1;i++)parts.push(enc.nextPart());parts[parts.length-1]=mutate(parts.at(-1),p=>p._fragment[3]^=1);rejected(()=>A.Pv(parts.join('\n')),/Conflicting/)});
test('D5 multipart transfer cannot be replaced by complete single QR',()=>{const single=new A.x_.UREncoder(new A.x_.UR(Buffer.from(A.S_(raw)),'crypto-psbt'),9999).nextPart();const s=new A.E_();s.feed(frames[0]);rejected(()=>s.feed(single),/identity/)});
for(const [name,fn] of [['oversized length',p=>p._messageLength=9007199254740991],['zero length',p=>p._messageLength=0],['wrong declared geometry',p=>p._messageLength=1],['header sequence mismatch',p=>p._seqNum=99]])test('D5 reject '+name+' before result',()=>{const value=mutate(frames[0],fn);rejected(()=>new A.E_().feed(name==='header sequence mismatch'?value.replace('/99-','/1-'):value))});
test('D5 valid frames arrive out of order',()=>assert.equal(hex(A.Pv([...frames].reverse().join('\n')).bytes),tx));
const payload=A.Ra.encode(raw),splits=payload.match(/.{1,120}/g),specter=splits.map((s,i)=>`p${i+1}of${splits.length} ${s}`);
for(const [name,tail] of [['conflict',specter[0].slice(0,-1)+'Z'],['arbitrary tail','junk'],['different format',frames[0]],['different count','p1of99 AA==']])test('R2 finite Specter rejects trailing '+name,()=>rejected(()=>A.Pv(specter.join('\n')+'\n'+tail)));
test('R2 Specter duplicates and reverse order remain supported',()=>assert.equal(hex(A.Pv([...specter].reverse().concat(specter[0]).join('\n')).bytes),tx));
test('finite UR incomplete cannot be verified',()=>rejected(()=>A.Pv(frames.slice(0,-1).join('\n')),/Incomplete/));
test('finite size budget accounts for whitespace',()=>rejected(()=>A.Pv(' '.repeat(1048577)+tx),/limit/));
test('D5 received frame and work budgets latch failure',()=>{const s=new A.E_();for(let i=0;i<4096;i++)s.feed(frames[0]);rejected(()=>s.feed(frames[1]),/limit/);const t=new A.E_();t.urWork=A.TBW_LIMITS.work;rejected(()=>t.feed(frames[0]),/work limit/)});
test('D1 signed PSBT v2 expected metadata classified separately',()=>{const r=check(signed());assert(r.ok&&r.matched);assert.equal(r.metadata.status,'expected');assert.equal(r.metadata.unexpected,0);assert.equal(r.metadata.fields.filter(f=>f.field==='partialSig').length,2)});
test('D1 signed PSBT v0 expected metadata classified separately',()=>{const r=check(signed(0),0);assert(r.ok&&r.matched);assert.equal(r.metadata.unexpected,0)});
test('D1 finalization metadata removals are expected',()=>{const p=signed();p.finalize();const r=check(p);assert(r.ok&&r.matched);assert.equal(r.metadata.unexpected,0);assert(r.metadata.fields.some(f=>f.change==='removed'))});
for(const scope of ['global','input','output'])test('D1 added proprietary '+scope+' marker visible without false malware verdict',()=>{const p=signed(),mark=[[Uint8Array.of(1,120,0),Uint8Array.of(65,66)]];if(scope==='global')p.global.proprietary=mark;else if(scope==='input')p.inputs[0].proprietary=mark;else p.outputs[0].proprietary=mark;const r=check(p);assert(r.ok&&r.matched);assert.equal(r.metadata.status,'unexpected');assert(r.metadata.fields.some(f=>f.classification==='unexpected'&&f.scope===scope))});
test('D1 changed output derivation is visible',()=>{const p=signed();p.outputs[0].bip32Derivation[0][1].path[4]++;const r=check(p);assert(r.ok&&r.matched);assert.equal(r.metadata.unexpected,1)});
test('D1 unsupported output witness script is visible separately',()=>{const p=signed();p.outputs[0].witnessScript=Uint8Array.of(81);const r=check(p);assert(r.ok&&r.matched);assert.equal(r.metadata.status,'unexpected')});
test('D1 raw transaction never implies PSBT metadata was checked',()=>{const r=A.zp(spec,{kind:'tx',bytes:raw},refs,root);assert.equal(r.metadata.status,'not-applicable')});
test('D1 trailing empty PSBT map is rejected rather than silently ignored',()=>{const b=signed().toPSBT(2),r=A.zp(spec,{kind:'psbt',bytes:Uint8Array.from([...b,0])},refs,root);assert(!r.ok);assert.match(r.error,/trailing maps/)});
test('D1 missing map rejected',()=>{const b=signed().toPSBT(2);assert(!A.zp(spec,{kind:'psbt',bytes:b.slice(0,-1)},refs,root).ok)});
test('D1 conversion v0 to v2 changes representation not transaction',()=>{const r=A.zp({...spec,psbtVersion:0},{kind:'psbt',bytes:signed(2).toPSBT(2)},refs,root);assert(r.ok&&r.matched);assert(r.metadata.versionConversion);assert.equal(r.metadata.unexpected,0)});
for(const [name,fn] of [['wrong input amount',p=>p.inputs[0].witnessUtxo.amount++],['wrong input derivation',p=>p.inputs[0].bip32Derivation[0][1].path[4]++],['different output amount',p=>p.outputs[0].amount--],['unsupported sighash',p=>p.inputs[0].sighashType=2],['no signature',p=>delete p.inputs[0].partialSig],['corrupt signature',p=>p.inputs[0].partialSig[0][1][10]^=1],['unsupported witness script',p=>p.inputs[0].witnessScript=Uint8Array.of(81)]])test('core rejects '+name,()=>{const p=signed();fn(p);assert(!check(p).ok)});
test('core published Dark Skippy signatures remain valid and differ',()=>{const r=A.Up();assert(r.ok&&!r.matched);assert.equal(r.evidence.signaturesVerified,2)});
test('D4 fixed algorithms select only their explicit expected references',()=>{for(const policy of ['plain','grind-core','grind-embit']){const subset=A.tbwPolicyReferences(refs,policy);assert(subset.every(r=>r.ids.includes(policy)));const r=A.zp(spec,{kind:'tx',bytes:bytes(subset[0].txHex)},subset,root);assert(r.ok&&r.matched)}});
test('D4 unsupported policy fails closed',()=>rejected(()=>A.tbwPolicyReferences(refs,'device-auto')));
test('D2 completed report and evidence share the frozen snapshot without seed',()=>{const a=app();a.acceptArtifact(tx);assert.equal(a.resultState,'match');const r=a.report(),ev=a.exportEvidence();assert(Object.isFrozen(r)&&Object.isFrozen(ev)&&Object.isFrozen(ev.publicTest));assert.strictEqual(ev.report,r);const json=JSON.stringify(ev);assert(!json.includes(spec.mnemonic));assert(!json.includes(root.privateExtendedKey));assert(!json.includes(hex(root.privateKey)));assert.equal(ev.returnedArtifact.hex,tx);assert.equal(ev.publicTest.inputs.length,2);assert.equal(ev.submission.text,tx);a.device='changed after verification';assert.notEqual(a.report().device,a.device);if(OUT)fs.writeFileSync(OUT.replace(/\.json$/,'-public-evidence.json'),JSON.stringify(ev,null,2));a.destroy()});
test('D2 incomplete valid-byte signature import retains evidence without a success',()=>{const a=app();const bad=bytes(tx);bad[bad.length-10]^=1;a.acceptArtifact(hex(bad));assert.equal(a.resultState,'incomplete');assert(a.hasEvidence);assert.equal(a.exportEvidence().report.result,'incomplete');a.destroy()});
test('D2 UI snapshot and report do not silently follow changed form',()=>{const a=app();a.acceptArtifact(tx);a.inputs[0].amount.value='99';assert.equal(a.resultState,'unverified');assert(!a.hasEvidence);rejected(()=>a.report());a.destroy()});
test('D3 repeated recompute and presentation changes reuse immutable prepared test',()=>{const a=app(),rev=a.preparedRevision,variants=a.variants;for(let i=0;i<15;i++){a.amountUnit=i%2?'sats':'btc';a.recompute();}assert.equal(a.preparedRevision,rev);assert.strictEqual(a.variants,variants);assert(Object.isFrozen(a.variants));a.destroy()});
test('D3 pending edit immediately hides old readiness before recompute',()=>{const a=app(),old=a.psbtBase64;a.outputs[0].amount.value='56000';assert(!a.transactionReady);a.recompute();assert(a.transactionReady);assert.notEqual(a.psbtBase64,old);a.destroy()});
test('D3 unchanged failed preparation does not retry automatically',()=>{const a=app();a.seed.value='invalid';a.recompute();const revision=a.preparedRevision;assert(a.buildProblem);a.recompute();assert.equal(a.preparedRevision,revision);a.apply();assert(a.preparedRevision>revision);a.destroy()});
test('D4 profile locks on an attempt; new transaction explicitly unlocks',()=>{const a=app();a.setSigningPolicy('plain');assert.equal(a.signingPolicy,'plain');a.acceptArtifact('bad');a.setSigningPolicy('grind-core');assert.equal(a.signingPolicy,'plain');a.randomizeTransaction("small");assert(!a.policyLocked);a.setSigningPolicy('grind-core');assert.equal(a.signingPolicy,'grind-core');a.destroy()});
test('D2 completed tests cannot be overwritten and duplicate returns do not advance ledger',()=>{const a=app();a.acceptArtifact(tx);const r=a.report();a.acceptArtifact(A.Vp);assert.strictEqual(r,a.report());assert.equal(a.sessionChecks.length,1);a.randomizeTransaction("small");assert.equal(a.resultState,'unverified');assert.equal(a.sessionChecks.length,1);a.destroy()});
test('Q2 UUID generation does not depend on randomUUID and has v4 variant bits',()=>{const {A:B}=load(FILE,{crypto:{getRandomValues:v=>require('crypto').webcrypto.getRandomValues(v)}});for(let i=0;i<30;i++)assert.match(B.tbwUUID(),/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/)});
test('Q2 missing secure randomness cannot create wallet',()=>{const {A:B}=load(FILE,{crypto:{}});rejected(()=>B.Fv());rejected(()=>B.tbwUUID(),/randomness/)});
const out={complete:true,testRange:range,totalDefined:testIndex,suite:'Audit regression, state, metadata and evidence contracts',passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length,results};if(OUT)fs.writeFileSync(OUT,JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));process.exitCode=out.failed?1:0;
