'use strict';
// New behavior regressions. Existing mathematical verifier remains the production authority.
const fs=require('fs'),cp=require('child_process'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),{load}=require('./load.cjs');
const FILE=process.argv[2],OUT=process.argv[3],{A,ctx}=load(FILE),results=[];let index=0;
const range=(process.env.TEST_RANGE||'1:999').split(':').map(Number);
function test(name,fn){index++;if(index<range[0]||index>range[1])return;try{fn();results.push({id:index,name,status:'passed'});console.log('PASS',index,name)}catch(e){results.push({id:index,name,status:'failed',error:e.stack});console.error('FAIL',index,name,e.message)}}
const hex=x=>A.K.encode(x),bytes=x=>A.K.decode(x),bw=A.__().default;
const oracle=JSON.parse(cp.execFileSync('python',[path.join(__dirname,'bytewords_oracle.py')],{encoding:'utf8',env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}}));
const spec=A.Hp(),root=A.up(spec.mnemonic),refs=A.Np(spec,root),tx=refs[0].txHex,raw=bytes(tx),good=A.w_(raw,90);
function code(fn,id){assert.throws(fn,e=>e.code===id,`Expected ${id}`)}
function corrupt(frame){const a=frame.split('/'),body=a.at(-1),k=body.slice(0,2);a[a.length-1]=(k==='ae'?'ad':'ae')+body.slice(2);return a.join('/')}
const bad=corrupt(good[0]);
function mutate(frame,fn){const a=frame.split('/'),p=A.g_().FountainEncoderPart.fromCBOR(bw.decode(a.at(-1),bw.STYLES.MINIMAL));fn(p);return A.x_.UREncoder.encodePart(a[0].slice(3),p)}
function signed(version=2,final=false){const p=A.wp({...spec,psbtVersion:version},root),r=A.ap.fromRaw(raw);for(let i=0;i<spec.inputs.length;i++){const w=r.getInput(i).finalScriptWitness;p.updateInput(i,{partialSig:[[w[1],w[0]]]},true)}if(final)p.finalize();return p}
function reduced(version=2,final=false){const p=signed(version,final);p.inputs=p.inputs.map(v=>Object.fromEntries(Object.entries(v).filter(([k])=>['txid','index','sequence','partialSig','finalScriptWitness','finalScriptSig'].includes(k))));p.outputs=p.outputs.map(v=>({amount:v.amount,script:v.script}));return p}
function check(p,version=2){return A.zp({...spec,psbtVersion:version},{kind:'psbt',bytes:p.toPSBT(version)},refs,root)}
function app(){const a=A.Fv(),f=v=>({value:String(v),error:null});a.$refs={};a.$nextTick=async()=>{};a.seed=f(spec.mnemonic);a.lockTime=f(spec.lockTime);a.psbtVersion='2';a.inputs=spec.inputs.map((v,i)=>({id:i,utxoId:f(v.txid+':'+v.vout),amount:f(v.amountSats),pathSuffix:f('0h/'+v.change+'/'+v.addressIndex),sequence:f(v.sequence)}));a.outputs=[{id:9,amount:f(spec.outputs[0].amountSats),dest:f('m/84h/0h/0h/0/18')}];a.acknowledged=true;a.recompute();assert(a.transactionReady);return a;}

test('independent Bytewords dictionary/vector and CRC boundaries agree byte for byte',()=>{for(const v of oracle.bytewords){assert.equal(bw.decode(v.minimal,bw.STYLES.MINIMAL),v.hex,v.name);assert.equal(bw.encode(v.hex,bw.STYLES.MINIMAL),v.minimal,v.name)}});
test('independent systematic UR frames decode all supported types/sizes in reverse order',()=>{for(const v of oracle.systematic){const s=new A.E_();[...v.frames].reverse().forEach(f=>s.feed(f));assert.equal(hex(s.verify().bytes),v.hex,v.name)}});
test('case-insensitive UR transfer matches independently generated uppercase frames',()=>{for(const v of oracle.systematic){const s=new A.E_();v.frames.forEach(f=>s.feed(f.toUpperCase()));assert.equal(hex(s.verify().bytes),v.hex)}});
test('known corrupt Bytewords produces checksum error, not internal decoder error',()=>code(()=>A.tbwInspectUr(bad),'UR_FRAME_CHECKSUM'));
test('odd/incomplete Bytewords gets encoding classification',()=>code(()=>A.tbwInspectUr('ur:bytes/abc'),'UR_FRAME_ENCODING'));
test('unknown Bytewords pair gets encoding classification',()=>code(()=>A.tbwInspectUr('ur:bytes/zzzzzzzzzz'),'UR_FRAME_ENCODING'));
test('internal decoder exception is terminal even for a camera',()=>{const old=bw.decode;try{bw.decode=()=>{throw new Error('injected implementation fault')};const s=new A.E_({source:'camera'});code(()=>s.feed(good[0]),'UR_DECODER_INTERNAL');assert(s.status().failed);assert.equal(s.rejectedFrames,0)}finally{bw.decode=old}});
test('invalid internal decoder return cannot masquerade as capture damage',()=>{const old=bw.decode;try{bw.decode=()=>new Uint8Array(8);code(()=>A.tbwInspectUr(good[0]),'UR_DECODER_INTERNAL')}finally{bw.decode=old}});
test('finite input stays strict by default and cannot be converted to camera by state mutation',()=>{const s=new A.E_();assert.equal(s.source,'finite');assert.throws(()=>s.source='camera');code(()=>s.feed(bad),'UR_FRAME_CHECKSUM');assert(s.status().failed)});
test('one rejected camera frame never enters the decoder or establishes an identity',()=>{const s=new A.E_({source:'camera'}),status=s.feed(bad);assert(!status.done&&!status.failed);assert.equal(s.urDecoder,null);assert.equal(s.urIdentity,null);assert.equal(s.urParts.size,0);assert.equal(status.rejectedFrames,1);assert.equal(status.progress,0)});
test('damaged frame does not erase valid progress, then valid transfer completes',()=>{const s=new A.E_({source:'camera'});const before=s.feed(good[0]),decoder=s.urDecoder,identity=s.urIdentity;const after=s.feed(bad);assert.equal(after.progress,before.progress);assert.equal(s.urDecoder,decoder);assert.equal(s.urIdentity,identity);good.slice(1).forEach(f=>s.feed(f));assert.equal(hex(s.verify().bytes),tx);assert.equal(s.status().rejectedFrames,1)});
test('seven consecutive bad observations can be followed by valid data, without admitting any bad frame',()=>{const s=new A.E_({source:'camera'});for(let i=0;i<7;i++)s.feed(bad);good.forEach(f=>s.feed(f));assert.equal(hex(s.verify().bytes),tx);assert.equal(s.consecutiveRejected,0);assert.equal(s.rejectedFrames,7)});
test('eighth consecutive bad observation stops and cannot revive without explicit reset',()=>{const s=new A.E_({source:'camera'});for(let i=0;i<7;i++)s.feed(bad);code(()=>s.feed(bad),'UR_CAPTURE_LIMIT');code(()=>s.feed(good[0]),'QR_SESSION_FAILED');assert.equal(s.result,null);s.rollback();good.forEach(f=>s.feed(f));assert.equal(hex(s.verify().bytes),tx);assert.equal(s.rejectedFrames,0)});
test('twenty-four total rejects stop even when valid duplicate frames reset consecutive count',()=>{const s=new A.E_({source:'camera'});for(let i=0;i<23;i++){s.feed(bad);s.feed(good[0])}assert.equal(s.rejectedFrames,23);code(()=>s.feed(bad),'UR_CAPTURE_LIMIT');assert.equal(s.status().progress,0)});
test('empty observations do not reset the consecutive-invalid budget',()=>{const s=new A.E_({source:'camera'});for(let i=0;i<7;i++){s.feed(bad);s.feed(' ')}code(()=>s.feed(bad),'UR_CAPTURE_LIMIT')});
test('valid completed camera session does not disregard corrupt trailing data when fed directly',()=>{const s=new A.E_({source:'camera'});good.forEach(f=>s.feed(f));code(()=>s.feed(bad),'UR_FRAME_CHECKSUM');assert.equal(s.result,null)});
test('camera format size budget is not retryable corruption',()=>{const s=new A.E_({source:'camera'});code(()=>s.feed('ur:bytes/'+'a'.repeat(A.TBW_LIMITS.frame)),'QR_FRAME_SIZE');assert(s.status().failed)});
test('camera aggregate frame and text budgets are retained',()=>{const s=new A.E_({source:'camera'});s.frames=A.TBW_LIMITS.frames;code(()=>s.feed(bad),'QR_SESSION_LIMIT');const t=new A.E_({source:'camera'});t.receivedCharacters=A.TBW_LIMITS.characters;code(()=>t.feed(bad),'QR_SESSION_LIMIT')});
test('camera rejects checksum-valid malformed fountain header immediately',()=>{const s=new A.E_({source:'camera'});code(()=>s.feed(mutate(good[0],p=>p._messageLength=1)),'UR_SIZE');assert.equal(s.rejectedFrames,0)});
test('checksum-valid conflicting duplicate is terminal, never an optical retry',()=>{const s=new A.E_({source:'camera'});s.feed(good[0]);code(()=>s.feed(mutate(good[0],p=>p._fragment[3]^=1)),'UR_DUPLICATE');assert(s.status().failed)});
test('complete-message checksum failure remains terminal after valid frame-level checks',()=>{const s=new A.E_({source:'camera'}),f=[mutate(good[0],p=>p._fragment[3]^=1),...good.slice(1)];code(()=>f.forEach(x=>s.feed(x)),'UR_MESSAGE_CHECKSUM');assert.equal(s.rejectedFrames,0);assert.equal(s.result,null)});
test('different transfer identity is not silently recovered by a camera scan',()=>{const s=new A.E_({source:'camera'});s.feed(good[0]);code(()=>s.feed(mutate(good[0],p=>p._checksum=(p._checksum^1)>>>0)),'UR_IDENTITY')});
test('bad UR cannot be treated as noise in an accepted Specter transfer',()=>{const s=new A.E_({source:'camera'});s.feed('p1of2 AA==');code(()=>s.feed(bad),'QR_MIXED')});
for(const [label,submission] of [['prefix',[bad,...good]],['middle',[good[0],bad,...good.slice(1)]],['tail',[...good,bad]]])test('finite pasted/file UR rejects corrupt '+label+' without returning a result',()=>code(()=>A.Pv(submission.join('\n')),'UR_FRAME_CHECKSUM'));
test('diagnostic state contains only error identity/counts/hash, no raw frame or wallet secret',()=>{const s=new A.E_({source:'camera'});s.feed(bad);const d=JSON.stringify(s.status());assert(!d.includes(bad));assert(!d.includes(spec.mnemonic));assert.equal(s.lastFrameIssue.frameSha256,crypto.createHash('sha256').update(bad).digest('hex'));assert.equal(s.lastFrameIssue.characters,bad.length)});
for(const version of [0,2])for(const final of [false,true])test(`uniform reduced PSBT v${version} ${final?'final witness':'partial signatures'} matches and has a documented non-warning assessment`,()=>{const p=reduced(version,final),r=check(p,version);assert(r.ok&&r.matched,JSON.stringify(r));assert.equal(r.metadata.status,'expected');assert(r.metadata.reducedResponse);assert.equal(r.metadata.supportingFieldsRemoved,5);assert.equal(r.metadata.unexpected,0);assert.equal(r.metadata.label,'Reduced signing response');assert(r.metadata.fields.some(f=>f.change==='removed'&&f.classification==='expected'))});
test('complete unchanged supporting metadata with added signatures still expected',()=>{const r=check(signed());assert(r.ok&&r.matched);assert(!r.metadata.reducedResponse);assert.equal(r.metadata.label,'Only expected signing changes')});
test('reduced v0/v2 conversion handled structurally without a device-name exemption',()=>{const p=reduced(0),r=A.zp(spec,{kind:'psbt',bytes:p.toPSBT(0)},refs,root);assert(r.ok&&r.matched);assert(r.metadata.versionConversion);assert.equal(r.metadata.unexpected,0)});
for(const [name,change] of [['one input amount-script removed',p=>delete p.inputs[0].witnessUtxo],['one input derivation removed',p=>delete p.inputs[0].bip32Derivation],['only output derivation removed',p=>delete p.outputs[0].bip32Derivation],['changed output derivation',p=>p.outputs[0].bip32Derivation[0][1].path[4]++]])test('selective/arbitrary '+name+' remains a review finding',()=>{const p=signed();change(p);const r=check(p);assert(r.ok&&r.matched);assert.equal(r.metadata.status,'unexpected');assert(r.metadata.unexpected>0);assert.equal(A.tbwFindingState('match',r.metadata),'review')});
for(const scope of ['global','input','output'])test('reduced response plus '+scope+' proprietary payload never receives a clean file assessment',()=>{const p=reduced(),entry=[[Uint8Array.of(1,120,0),Uint8Array.of(65,66)]];if(scope==='global')p.global.proprietary=entry;else if(scope==='input')p.inputs[0].proprietary=entry;else p.outputs[0].proprietary=entry;const r=check(p);assert(r.ok&&r.matched);assert.equal(r.metadata.status,'unexpected');assert(!r.metadata.reducedResponse)});
test('unexpected added output script in reduced file remains visible',()=>{const p=reduced();p.outputs[0].witnessScript=Uint8Array.of(81);const r=check(p);assert(r.ok&&r.matched);assert.equal(r.metadata.status,'unexpected')});
test('mixed partial and finalized input layouts do not qualify for uniform reduction',()=>{const p=reduced(),f=reduced(2,true);p.inputs[0]=f.inputs[0];const r=check(p);assert(r.ok&&r.matched);assert.equal(r.metadata.status,'unexpected')});
for(const [name,change] of [['invalid signature',p=>p.inputs[0].partialSig[0][1][10]^=1],['missing signature',p=>delete p.inputs[0].partialSig],['wrong signing key',p=>p.inputs[0].partialSig[0][0]=root.publicKey],['changed recipient amount',p=>p.outputs[0].amount--],['changed locktime',p=>p.global.fallbackLocktime++],['changed UTXO',p=>p.inputs[0].txid[0]^=1]])test('reduced metadata recognition cannot turn '+name+' into a completed result',()=>{const p=reduced();change(p);const r=check(p);assert(!r.ok,JSON.stringify(r));assert(!r.metadata);assert.equal(A.tbwFindingState('incomplete',r.metadata),'incomplete')});
test('published malicious-signature example remains a mismatch and is never amber-only',()=>{const r=A.Up();assert(r.ok&&!r.matched);assert.equal(A.tbwFindingState('mismatch',{status:'unexpected'}),'mismatch')});
test('raw response file check is not applicable, not missing support-data approval',()=>{const r=A.zp(spec,{kind:'tx',bytes:raw},refs,root);assert(r.ok&&r.matched);assert.equal(r.metadata.status,'not-applicable')});
test('immutable saved finding distinguishes matching signatures from overall review',()=>{const a=app(),p=signed();p.outputs[0].bip32Derivation[0][1].path[4]++;a.acceptArtifact(hex(p.toPSBT(2)));assert.equal(a.resultState,'match');assert.equal(a.resultDisplayState,'review');const r=a.report();assert.equal(r.result,'match');assert.equal(r.overallStatus,'review');assert.equal(a.exportEvidence().report.overallStatus,'review');assert(Object.isFrozen(r));a.destroy()});
test('reduced-file explanation matches an immutable successful public report',()=>{const a=app();a.acceptArtifact(hex(reduced().toPSBT(2)));assert.equal(a.resultState,'match');assert.equal(a.resultDisplayState,'match');assert(a.metadataExplanation.includes('original'));assert.equal(a.report().metadata.supportingFieldsRemoved,5);assert.equal(a.report().overallStatus,'match');assert(!JSON.stringify(a.exportEvidence()).includes(spec.mnemonic));a.destroy()});
test('camera rejected-frame diagnostics persist into report and evidence',()=>{const a=app(),s=new A.E_({source:'camera'});s.feed(bad);good.forEach(f=>s.feed(f));a.acceptArtifact(tx,{method:'camera',transport:{...s.status(),completeSubmission:false}});assert.equal(a.report().transport.rejectedFrames,1);assert.equal(a.exportEvidence().submission.transport.rejectedFrames,1);assert(a.completedScanNote.includes('1'));a.destroy()});
test('standalone scan diagnostics excludes local wallet and raw scanned data',()=>{const a=app(),s=new A.E_({source:'camera'});s.feed(bad);a.scan.diagnostics=s.status();const d=a.scanDiagnostics();assert.equal(d.schema,'tbw-scan-diagnostics-v1');assert(!JSON.stringify(d).includes(spec.mnemonic));assert(!JSON.stringify(d).includes(bad));assert(Object.isFrozen(d));a.destroy()});
test('new-test invalidation clears stale scanner diagnostic state',()=>{const a=app();a.scan.diagnostics={rejectedFrames:1};a.invalidate();assert.equal(a.scan.diagnostics,null);a.destroy()});
const out={suite:'QR capture and returned-file remediation regressions',test_range:range.join(':'),total_defined:index,artifact:path.basename(FILE),sha256:crypto.createHash('sha256').update(fs.readFileSync(FILE)).digest('hex'),passed:results.filter(x=>x.status==='passed').length,failed:results.filter(x=>x.status==='failed').length,results};fs.writeFileSync(OUT,JSON.stringify(out,null,2));console.log('TOTAL',out.passed,out.failed);process.exitCode=out.failed?1:0;
