'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const {load}=require('./load.cjs'),FILE=process.argv[2],OUT=process.argv[3],{A,ctx}=load(FILE);
const results=[],range=(process.env.TEST_RANGE||'1:999').split(':').map(Number);let index=0;
const J=A.TbwSessionJournal,root=A.up('abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about');
const context={walletSession:'disposable-test-session',rootPublicKey:A.K.encode(root.publicKey),fingerprint:'73C5DA0A',policy:'compatible',psbtVersion:'0'};
const field=v=>({value:String(v),error:null});let serial=0;
function makeCase(){serial++;return {scenario:'small',lockTime:field(0),inputs:[{id:1,utxoId:field(serial.toString(16).padStart(64,'0')+':0'),amount:field(10000),pathSuffix:field('0h/0/0'),sequence:field('4294967293')}],outputs:[{id:2,amount:field(9500),dest:field('m/84h/0h/0h/1/0')}]};}
function begin(count=2){const journal=new J(),p=journal.plan(count,context,makeCase);journal.apply(p);return journal;}
function report(outcome='match',metadata='expected',number=1){return {completed:outcome!=='incomplete',result:outcome,test:number,scenario:'small',createdAt:'2026-09-16T00:00:00Z',evidence:outcome==='incomplete'?null:{transactionId:String(number).padStart(64,'0'),artifactSha256:'b'.repeat(64),signaturesVerified:1},signingPolicy:{id:'compatible'},matchedAlgorithms:outcome==='match'?['plain']:[],metadata:{status:metadata},error:outcome==='incomplete'?'Invalid test response':null};}
function binding(j){return {...context,caseNumber:j.status().current,caseIdentity:j.currentCase().identity};}
function equal(a,b){assert.equal(JSON.stringify(a),JSON.stringify(b));}
function test(name,fn){index++;if(index<range[0]||index>range[1])return;const t=performance.now();console.log('RUN',index,name);try{fn();results.push({name,status:'passed',ms:Math.round(performance.now()-t)});}catch(e){results.push({name,status:'failed',error:e.stack});}}
for(const count of [1,20,50,100,200])test('C2 count and immutable distinct balanced plan '+count,()=>{const j=new J();const p=j.plan(count,context);assert.equal(p.cases.length,count);assert.equal(new Set(p.cases.map(c=>c.identity)).size,count);assert(Object.isFrozen(p.cases[0].form.inputs));const counts=Object.values(p.cases.reduce((m,c)=>(m[c.form.scenario]=(m[c.form.scenario]||0)+1,m),{}));assert(Math.max(...counts)-Math.min(...counts)<=1);assert.equal(j.status().phase,'manual');const {sha256,...data}=p;assert.equal(sha256,crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex'));assert(!JSON.stringify(p).includes('mnemonic'));});
test('C2 invalid counts never mutate the journal',()=>{for(const n of ['',0,-1,201,1.5,'1e2',' 20','020',NaN,Infinity,true,null]){const j=new J();assert.throws(()=>j.plan(n,context));assert.equal(j.status().hasPlan,false)}});
test('C2 externally supplied/copied plans are rejected',()=>{const a=new J(),b=new J(),p=a.plan(2,context,makeCase);assert.throws(()=>a.apply(JSON.parse(JSON.stringify(p))));assert.throws(()=>b.apply(p));a.apply(p);assert.throws(()=>a.apply(p))});
test('C2 a generation failure leaves no applied plan or results',()=>{const j=new J();const before=j.status();assert.throws(()=>j.plan(5,context,()=>{throw Error('injected RNG failure')}));equal(j.status(),before);j.apply(j.plan(2,context,makeCase));assert.equal(j.status().current,1)});
test('C2 duplicate generated transactions reject the entire plan',()=>{const j=new J(),c=makeCase();assert.throws(()=>j.plan(2,context,()=>c),/repeated/);assert(!j.hasPlan)});
test('C3 every advance requires a prior checked response',()=>{const j=begin(2);assert.throws(()=>j.advance());j.record(report());assert.equal(j.status().phase,'ready');assert.equal(j.status().current,1);j.advance();assert.equal(j.status().current,2);assert.throws(()=>j.advance());assert.equal(j.status().completed,1)});
test('C3 full 200-case controller simulation never performs signing or automatic advancement',()=>{const j=begin(200);for(let i=1;i<=200;i++){assert.equal(j.status().current,i);assert.equal(j.status().completed,i-1);j.record(report('match','expected',i));assert.equal(j.status().current,i);if(i<200)j.advance();}assert.equal(j.status().phase,'complete');assert.equal(j.status().matched,200);assert.equal(j.status().notCompleted,0);assert.throws(()=>j.advance());});
for(const [outcome,metadata] of [['mismatch','expected'],['match','unexpected'],['incomplete','expected']])test('C4 halt survives more data and Next: '+outcome+'/'+metadata,()=>{const j=begin();j.record(report(outcome,metadata));assert.equal(j.status().phase,'halted');const old=j.report();assert.throws(()=>j.record(report()));assert.throws(()=>j.advance());equal(j.report(),old);j.rollback('Investigating');assert.equal(j.status().phase,'ended');assert.equal(j.report().events.length,2);});
test('C4 capture failure is recorded once and never automatically revived',()=>{const j=begin();assert(j.halt('No camera','capture-error','CAMERA_ERROR'));assert(!j.halt('late callback','capture-error'));assert.equal(j.status().captureFailures,1);assert.throws(()=>j.record(report()));assert.throws(()=>j.advance());});
for(const key of ['walletSession','rootPublicKey','policy','psbtVersion','caseIdentity','caseNumber'])test('C7 binding rejects changed '+key,()=>{const j=begin();assert(j.verify(binding(j)));assert.throws(()=>j.verify({...binding(j),[key]:'changed'}));});
test('C5 unique transaction summary is a read-only projection with sticky differences',()=>{const j=new J();j.record(report('match'));j.record(report('mismatch'));j.record(report('match'));assert.equal(j.checks().length,1);assert.equal(j.checks()[0].result,'mismatch');assert(Object.isFrozen(j.checks()));assert.throws(()=>j.checks().push({}));});
test('C5 incomplete results do not increase distinct completed counts',()=>{const j=new J();j.record(report('incomplete'));assert.equal(j.checks().length,0)});
test('C6 report uses an explicit public allowlist and preserves old snapshots',()=>{const j=begin(),r=report();r.mnemonic='SECRET';r.privateKey='PRIVATE';r.reactiveApp={seed:'ROOT'};j.record(r);const before=j.report(),text=JSON.stringify(before);for(const forbidden of ['SECRET','PRIVATE','ROOT','reactiveApp'])assert(!text.includes(forbidden));j.advance();assert.equal(JSON.stringify(before),text);assert.equal(j.report().deviceOrigin,'not-attested');assert(Object.isFrozen(before.events));});
test('C6 early ending preserves counts and all not-completed cases',()=>{const j=begin(50);j.record(report());j.advance();j.rollback('Device refused this test');assert.equal(j.status().completed,1);assert.equal(j.status().notCompleted,49);assert.equal(j.report().events[1].caseNumber,2);const old=j.report();j.rollback();equal(j.report(),old);});
test('C6 manual work after End cannot change the historical guided report',()=>{const j=begin();j.record(report('incomplete'));j.rollback();const before=j.report();j.record(report('match','expected',9));equal(j.report(),before);assert.equal(j.checks().length,1)});
test('C7 history memory bound rejects without dropping old entries',()=>{const j=new J();for(let n=0;n<2000;n++)j.record(report('incomplete'));assert(!j.canRecord);assert.throws(()=>j.record(report()),/history limit/);assert.equal(j.checks().length,0)});
test('C7 current plan identity ignores labels but not transaction fields',()=>{const c=makeCase(),f=A.tbwFormCase(c,'0'),hash=A.tbwCaseIdentity(f);f.scenario='different label';assert.equal(A.tbwCaseIdentity(f),hash);f.outputs[0].amount='9000';assert.notEqual(A.tbwCaseIdentity(f),hash)});
test('C7 optional planner absence leaves manual result bookkeeping usable',()=>{const saved=vm.runInContext('tbwMakeGuidedPlan',ctx);vm.runInContext('tbwMakeGuidedPlan=undefined',ctx);try{const j=new J();j.record(report());assert.equal(j.checks().length,1);assert.throws(()=>new J().plan(2,context),/unavailable/);}finally{ctx.savedPlanner=saved;vm.runInContext('tbwMakeGuidedPlan=savedPlanner;delete savedPlanner',ctx)}});
// Application integration uses bounded deterministic fixture shapes, not random expensive
// boundary signing. Independent six-scenario tests retain full construction coverage.
const original=vm.runInContext('jv',ctx);ctx.fixtureFactory=makeCase;vm.runInContext('jv=fixtureFactory',ctx);
function app(){const a=A.Fv();a.$refs={};a.$nextTick=async()=>{};a.seed={value:'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about',error:null};const c=makeCase();a.lockTime=c.lockTime;a.inputs=c.inputs;a.outputs=c.outputs;a.generatedScenario=c.scenario;a.generatedShape='fixture';a.acknowledged=true;a.recompute();assert(a.transactionReady,a.buildProblem);return a;}
test('C1 missing seed canvas has no misleading available fingerprint',()=>{const a=app();assert.equal(a.walletFingerprint,'');a.destroy();assert.equal(a.walletFingerprint,'')});
test('C3 application uses the same verifier for manual and planned responses',()=>{const a=app();a.sessionCount='2';a.startGuidedSession();assert.equal(a.guidedStatus.phase,'receiving',a.notice);const psbt=a.psbtBase64,tx=a.variants[0].txHex;const direct=A.zp({...a.buildSpec().spec},{kind:'tx',bytes:A.K.decode(tx)},A.Np(a.buildSpec().spec),undefined,A.K.encode(A.Ra.decode(psbt)));a.acceptArtifact(tx);assert.equal(a.resultState,'match');assert.equal(a.analysis.txHex,direct.txHex);assert.equal(a.guidedStatus.completed,1);assert.equal(a.report().physicalSession.caseNumber,1);a.destroy()});
test('C7 repeated Start/Next/import cannot duplicate a planned case',()=>{const a=app();a.sessionCount='2';a.startGuidedSession();const id=a.guidedStatus.planId,first=a.psbtBase64;a.startGuidedSession();a.advanceGuidedSession();assert.equal(a.psbtBase64,first);a.acceptArtifact(a.variants[0].txHex);a.verify();a.acceptArtifact('bad');assert.equal(a.guidedStatus.completed,1);a.advanceGuidedSession();const second=a.psbtBase64;a.advanceGuidedSession();assert.equal(a.psbtBase64,second);assert.equal(a.guidedStatus.current,2);assert.equal(a.guidedStatus.planId,id);a.destroy()});
test('C4 wrong-test data stops the application and cannot be silently retried',()=>{const a=app();a.sessionCount='2';a.startGuidedSession();const old=a.variants[0].txHex;a.acceptArtifact(old);a.advanceGuidedSession();const next=a.variants[0].txHex;a.acceptArtifact(old);assert.equal(a.resultState,'incomplete');assert.equal(a.guidedStatus.phase,'halted');const result=a.report();a.acceptArtifact(next);a.advanceGuidedSession();assert.strictEqual(a.report(),result);assert.equal(a.guidedStatus.completed,1);a.endGuidedSession();const saved=JSON.stringify(a.exportSessionReport());a.acceptArtifact(next);assert.equal(a.resultState,'match');assert.equal(JSON.stringify(a.exportSessionReport()),saved);a.destroy()});
test('C7 planned wallet and transaction mutation paths are locked',()=>{const a=app();a.sessionCount='2';a.startGuidedSession();const before=a.stateSignature;for(const fn of [()=>a.randomizeAll(),()=>a.selectSeedLength(24),()=>a.setSigningPolicy('plain'),()=>a.setRandomLockTime(),()=>a.addInputRow(),()=>a.removeInputRow(0),()=>a.generateRandomInputs(),()=>a.addOutputRow(),()=>a.removeOutputRow(0),()=>a.generateRandomOutputs(),()=>a.randomizeTransaction('small')]){fn();assert.equal(a.stateSignature,before);}a.destroy()});
test('C7 out-of-band form tampering halts rather than rebuilding a different planned test',()=>{const a=app();a.startGuidedSession();const original=a.psbtBase64;a.outputs[0].amount.value='9000';a.recompute();assert.equal(a.guidedStatus.phase,'halted');assert(!a.transactionReady);assert.equal(a.psbtBase64,original);a.destroy()});
test('C7 invalid setup leaves manual workflow byte-for-byte unchanged',()=>{const a=app(),before=a.stateSignature,psbt=a.psbtBase64;a.sessionCount='201';a.startGuidedSession();assert(!a.hasGuidedSession);assert.equal(a.stateSignature,before);assert.equal(a.psbtBase64,psbt);a.acceptArtifact(a.variants[0].txHex);assert.equal(a.resultState,'match');a.destroy()});
test('C6 session report excludes locally held seed and private material',()=>{const a=app();a.startGuidedSession();a.acceptArtifact(a.variants[0].txHex);const json=JSON.stringify(a.exportSessionReport());for(const bad of [a.seed.value,A.K.encode(root.privateKey),root.privateExtendedKey,'stateKey','artifactText'])assert(!json.includes(bad));a.destroy()});
test('C4 a valid but different fixed-method response halts even on the final case',()=>{const a=app(),spec=A.Hp();const form=()=>({scenario:'small',lockTime:field(spec.lockTime),inputs:spec.inputs.map((x,i)=>({id:i,utxoId:field(x.txid+':'+x.vout),amount:field(x.amountSats),pathSuffix:field(x.account+'h/'+x.change+'/'+x.addressIndex),sequence:field(x.sequence)})),outputs:[{id:10,amount:field(spec.outputs[0].amountSats),dest:field('m/84h/0h/0h/0/18')}]});ctx.newFactory=form;vm.runInContext('jv=newFactory',ctx);try{a.seed.value=spec.mnemonic;const f=form();a.inputs=f.inputs;a.outputs=f.outputs;a.lockTime=f.lockTime;a.recompute();a.setSigningPolicy('plain');a.sessionCount='1';a.startGuidedSession();const other=a.variants.find(r=>!r.ids.includes('plain'));assert(other);a.acceptArtifact(other.txHex);assert.equal(a.resultState,'mismatch');assert.equal(a.guidedStatus.phase,'halted');assert.equal(a.guidedStatus.differed,1);assert.equal(a.guidedStatus.matched,0);assert.equal(a.guidedStatus.notCompleted,0);}finally{vm.runInContext('jv=fixtureFactory;delete newFactory',ctx);a.destroy();}});
vm.runInContext('jv=undefined',ctx);ctx.original=original;vm.runInContext('jv=original;delete original;delete fixtureFactory',ctx);
const output={suite:'Consolidation / guided physical-session contracts and faults',complete:true,testRange:range,totalDefined:index,passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length,sha256:crypto.createHash('sha256').update(fs.readFileSync(FILE)).digest('hex'),results};fs.writeFileSync(OUT,JSON.stringify(output,null,2));console.log(JSON.stringify({passed:output.passed,failed:output.failed,failures:results.filter(r=>r.status==='failed')}));process.exitCode=output.failed?1:0;
